const editor=document.querySelector('#editor');const keyboard=document.querySelector('#keyboard');const count=document.querySelector('#count');const toast=document.querySelector('#toast');let shifted=false;let savedLanguage=localStorage.getItem('typingLanguage');let typingLanguage=['ksw','pwo','en'].includes(savedLanguage)?savedLanguage:'ksw';
// KarenKNU S'gaw Karen Unicode map: [English key, normal, shifted].
const rows=[
[['`','ပ','ြု'],['1','၁','ည'],['2','၂','ၥ'],['3','၃','£'],['4','၄','၃'],['5','၅','ရ'],['6','၆','၄'],['7','၇','ရ'],['8','၈','ဂ'],['9','၉','('],['0','ဝ',')'],['-','ြ','ြ'],['=','—','ှု']],
[['q','ဆ','ခ'],['w','တ','တ'],['e','န','န'],['r','မ','ၤ'],['t','အ','၎'],['y','ပ','၌'],['u','က','ၢ'],['i','င','ၢ်'],['o','သ','ၣ်'],['p','စ','ာ်'],['[','ဟ','ဧ'],[']','=','ဂ'],['\\','ၪ','ၑ']],
[['a','ေ','∕'],['s','ျ','ှ'],['d','ိ','ီ'],['f','်','ၠ'],['g','ါ','ွ'],['h','့','ံ'],['j','ြ','ဲ'],['k','ု','ု'],['l','ူ','ူ'],[';','း','ၤ'],["'",'ဒ','ီ']],
[['z','ဖ','ဇ'],['x','ထ','ဌ'],['c','ခ','ဃ'],['v','လ','ျ့'],['b','ဘ','ြ'],['n','ည','ဒ'],['m','ာ်','ျ့'],[',','ယ',','],['.','ၣ်','ၢ်'],['/','”','“']]
];
const englishRows=[
[['`','`','~'],['1','1','!'],['2','2','@'],['3','3','#'],['4','4','$'],['5','5','%'],['6','6','^'],['7','7','&'],['8','8','*'],['9','9','('],['0','0',')'],['-','-','_'],['=','=','+']],
[['q','q','Q'],['w','w','W'],['e','e','E'],['r','r','R'],['t','t','T'],['y','y','Y'],['u','u','U'],['i','i','I'],['o','o','O'],['p','p','P'],['[','[','{'],[']',']','}'],['\\','\\','|']],
[['a','a','A'],['s','s','S'],['d','d','D'],['f','f','F'],['g','g','G'],['h','h','H'],['j','j','J'],['k','k','K'],['l','l','L'],[';',';',':'],["'","'",'"']],
[['z','z','Z'],['x','x','X'],['c','c','C'],['v','v','V'],['b','b','B'],['n','n','N'],['m','m','M'],[',',',','<'],['.','.','>'],['/','/','?']]
];
// Keyman Eastern Pwo Karen 1.1 Unicode map: [English key, normal, shifted].
const pwoRows=[
[['`','`','~'],['1','၁','ဠ'],['2','၂','ဎ'],['3','၃','ဋ'],['4','၄','$'],['5','၅','%'],['6','၆','^'],['7','၇','ရ'],['8','၈','*'],['9','၉','('],['0','ဝ',')'],['-','-','_'],['=','=','+']],
[['q','ဆ','ဇ'],['w','တ','ဝ'],['e','န','ၞ'],['r','မ','ၟ'],['t','အ','ဍ'],['y','ပ','ါဲ'],['u','က','ဥ'],['i','င','ၚ'],['o','သ','ဳ'],['p','စ','ဏ'],['[','ဟ','ၯ'],[']','☆','ၰ'],['\\','\\','|']],
[['a','ေ','ဗ'],['s','ျ','ှ'],['d','ိ','ီ'],['f','်','္'],['g','ါ','ွ'],['h','့','ံ'],['j','ြ','ဲ'],['k','ု','ဒ'],['l','ူ','ဓ'],[';','း','ဂ'],["'","'",'"']],
[['z','ဖ','ဈ'],['x','ထ','ဌ'],['c','ခ','ဃ'],['v','လ','ၠ'],['b','ဘ','ယ'],['n','ည','ဉ'],['m','ာ','ၜ'],[',',',','၊'],['.','ႋ','။'],['/','/','?']]
];
function rowsForLanguage(language=typingLanguage){return language==='en'?englishRows:language==='pwo'?pwoRows:rows}
function mappingsForLanguage(language=typingLanguage){return rowsForLanguage(language).flat().flatMap(([key,normal,shift])=>[{key,value:normal,shift:false},{key,value:shift,shift:true}]).sort((a,b)=>b.value.length-a.value.length)}
const special=[['Backspace','Backspace','⌫'],[' ','Space','Space'],['Enter','Enter','↵ Enter']];
function phoneKeyboard(){return window.matchMedia('(max-width:720px)').matches}
function makePhoneControl(label,display,action){const b=document.createElement('button');b.type='button';b.className='key phone-control';b.dataset.code=label;b.innerHTML=`<small>${label}</small>${display}`;b.addEventListener('click',action);return b}
function render(){keyboard.innerHTML='';const mobile=phoneKeyboard(),layout=rowsForLanguage();layout.forEach((row,rowIndex)=>{const el=document.createElement('div');el.className='key-row';if(mobile&&rowIndex===layout.length-1)el.appendChild(makePhoneControl('Shift','⇧',()=>setShift(!shifted)));row.forEach(([latin,normal,shift])=>el.appendChild(makeKey(latin,shifted?shift:normal)));if(mobile&&rowIndex===layout.length-1)el.appendChild(makePhoneControl('Backspace','⌫',()=>insert('Backspace')));keyboard.appendChild(el)});const bottom=document.createElement('div');bottom.className='key-row phone-bottom-row';special.filter(([value])=>!mobile||value!=='Backspace').forEach(([value,label,display])=>{const b=makeKey(label,display,value);b.classList.add('wide');if(value===' ')b.classList.add('space');bottom.appendChild(b)});keyboard.appendChild(bottom)}
function makeKey(label,char,value=char){const b=document.createElement('button');b.type='button';b.className='key';b.dataset.value=value;b.dataset.code=label;b.innerHTML=`<small>${label==='Space'?'':label}</small>${char}`;b.addEventListener('click',()=>insert(value));return b}
function previousTextBoundary(text,index){if(!index)return 0;if(typeof Intl.Segmenter==='function'){const segments=[...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(text.slice(0,index))];return segments.length?segments[segments.length-1].index:0}const points=Array.from(text.slice(0,index));return index-(points.pop()||'').length}
function insert(value){editor.focus();if(!editor.readOnly){if(value==='Backspace'){document.execCommand('delete');}else if(value==='Enter'){document.execCommand('insertText',false,'\n');}else{document.execCommand('insertText',false,value)}updateCount();return}const start=editor.selectionStart??editor.value.length,end=editor.selectionEnd??start;let replacement=value==='Enter'?'\n':value,next=start;if(value==='Backspace'){const from=start===end?previousTextBoundary(editor.value,start):start;editor.value=editor.value.slice(0,from)+editor.value.slice(end);next=from}else{editor.value=editor.value.slice(0,start)+replacement+editor.value.slice(end);next=start+replacement.length}editor.setSelectionRange(next,next);editor.dispatchEvent(new Event('input',{bubbles:true}))}
function updateCount(){const n=[...editor.value].length;count.textContent=`${n} ${n===1?'character':'characters'}`}
function setShift(on){shifted=on;document.querySelector('#normalMode').classList.toggle('active',!on);document.querySelector('#shiftMode').classList.toggle('active',on);render()}
document.querySelector('#normalMode').onclick=()=>setShift(false);document.querySelector('#shiftMode').onclick=()=>setShift(true);
function physicalKey(e){if(e.code.startsWith('Key'))return e.code.slice(3).toLowerCase();if(e.code.startsWith('Digit'))return e.code.slice(5);return({Backquote:'`',Minus:'-',Equal:'=',BracketLeft:'[',BracketRight:']',Backslash:'\\',Semicolon:';',Quote:"'",Comma:',',Period:'.',Slash:'/'}[e.code]||e.key.toLowerCase())}
editor.addEventListener('input',updateCount);editor.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Shift'){setShift(true);return}const key=physicalKey(e),match=rowsForLanguage().flat().find(([mapped])=>mapped===key);if(match){if(typingLanguage!=='en'){e.preventDefault();insert(e.shiftKey?match[2]:match[1])}flashKey(match[0])}});editor.addEventListener('keyup',e=>{if(e.key==='Shift')setShift(false)});
function flashKey(code){const b=[...document.querySelectorAll('.key')].find(k=>k.dataset.code===code);if(b){b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),110)}}
document.querySelector('#copy').onclick=async()=>{if(!editor.value){showToast('Type something first');return}try{await navigator.clipboard.writeText(editor.value)}catch{editor.select();document.execCommand('copy')}document.querySelector('#copyText').textContent='Copied';showToast('Copied to clipboard');setTimeout(()=>document.querySelector('#copyText').textContent='Copy text',1400)};
document.querySelector('#clear').onclick=()=>{if(!editor.value)return;editor.value='';updateCount();editor.focus();showToast('Text cleared')};document.querySelector('#selectAll').onclick=()=>{editor.focus();editor.select()};document.querySelector('#undo').onclick=()=>{editor.focus();document.execCommand('undo');updateCount()};document.querySelector('#toggleGuide').onclick=()=>{const g=document.querySelector('#guide');g.hidden=!g.hidden};
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
function languageName(){return typingLanguage==='en'?'English':typingLanguage==='pwo'?'Pwo Karen':'S’gaw Karen'}
function languageTag(){return typingLanguage==='en'?'en':typingLanguage==='pwo'?'kjp':'ksw'}
function updateLanguageInterface(){const english=typingLanguage==='en',pwo=typingLanguage==='pwo',name=languageName();document.querySelector('#languageKaren').classList.toggle('active',typingLanguage==='ksw');document.querySelector('#languagePwo').classList.toggle('active',pwo);document.querySelector('#languageEnglish').classList.toggle('active',english);document.querySelector('#typeEyebrow').textContent=english?'ENGLISH · QWERTY':pwo?'PWO KAREN · EASTERN PWO':'S’GAW KAREN · ကညီကျိာ်';document.querySelector('#editor-title').textContent=`Type in ${name}`;document.querySelector('#typeHint').textContent=english?'Standard QWERTY layout — use your keyboard or tap below.':pwo?'Keyman Eastern Pwo Karen layout — use your English keyboard or tap below.':'KarenKNU layout — use your English keyboard or tap below.';document.querySelector('#guide').textContent=english?'This is the standard English QWERTY layout. Press Shift for capital letters and symbols.':pwo?'This is the Keyman Eastern Pwo Karen 1.1 layout. Each key shows its English shortcut. Press Shift for the second layer.':'This is the KarenKNU S’gaw Karen layout. Each key shows its English shortcut. Press Shift for the second layer.';document.querySelector('#gamesEyebrow').textContent=`${name.toUpperCase()} TYPING GAMES`;document.querySelector('#gamesHint').textContent=`Practice ${name} while building speed and accuracy.`;document.querySelector('#practiceEyebrow').textContent=`${name.toUpperCase()} TYPING PRACTICE`;document.querySelector('[data-game="sprint"] small').textContent=`Type as many ${name} words as you can in 45 seconds.`;document.querySelector('[data-game="rain"] small').textContent=`Type each ${name} word before it reaches the bottom.`;editor.lang=languageTag();editor.placeholder=english?'Type here…':pwo?'Type Pwo Karen here…':'တီၢ်လံာ်ဖဲအံၤ…';setShift(false);render()}
function setTypingLanguage(language){typingLanguage=['ksw','pwo','en'].includes(language)?language:'ksw';localStorage.setItem('typingLanguage',typingLanguage);updateLanguageInterface();window.dispatchEvent(new CustomEvent('typinglanguagechange',{detail:{language:typingLanguage}}));if(!document.querySelector('#typeView').hidden)editor.focus()}
function configurePhoneEditor(){const mobile=phoneKeyboard();editor.readOnly=mobile;editor.inputMode=mobile?'none':'text';editor.setAttribute('aria-label',mobile?'Text editor. Use the on-screen keyboard below.':'Typing text editor')}
document.querySelector('#languageKaren').onclick=()=>setTypingLanguage('ksw');document.querySelector('#languagePwo').onclick=()=>setTypingLanguage('pwo');document.querySelector('#languageEnglish').onclick=()=>setTypingLanguage('en');configurePhoneEditor();updateLanguageInterface();updateCount();
window.addEventListener('resize',()=>{configurePhoneEditor();render()});
