const editor=document.querySelector('#editor');const keyboard=document.querySelector('#keyboard');const count=document.querySelector('#count');const toast=document.querySelector('#toast');let shifted=false;let typingLanguage=localStorage.getItem('typingLanguage')==='en'?'en':'ksw';
// KarenKNU S'gaw Karen Unicode map: [English key, normal, shifted].
const rows=[
[['`','ပ','ြု'],['1','၁','ည'],['2','၂','ၥ'],['3','၃','£'],['4','၄','၃'],['5','၅','ရ'],['6','၆','၄'],['7','၇','ရ'],['8','၈','ဂ'],['9','၉','('],['0','ဝ',')'],['-','ြ','ြ'],['=','—','ှု']],
[['q','ဆ','ခ'],['w','တ','တ'],['e','န','န'],['r','မ','ၤ'],['t','အ','၎'],['y','ပ','၌'],['u','က','ၢ'],['i','င','ၢ်'],['o','သ','ၣ်'],['p','စ','ာ်'],['[','ဟ','ဧ'],[']','=','ဂ'],['\\','ၪ','ၑ']],
[['a','ေ','∕'],['s','ျ','ှ'],['d','ိ','ီ'],['f','်','ၠ'],['g','ါ','ွ'],['h','့','ံ'],['j','ြ','ဲ'],['k','ု','ု'],['l','ူ','ူ'],[';','း','ၤ'],["'",'ဒ','ီ']],
[['z','ဖ','ဇ'],['x','ထ','ဌ'],['c','ခ','ဃ'],['v','လ','ျ့'],['b','ဘ','ြ'],['n','ည','ဒ'],['m','ာ်','ျ့'],[',','ယ',','],['.','ၣ်','ၢ်'],['/','”','“']]
];
const englishRows=[
[['`','`','~'],['1','1','!'],['2','2','@'],['3','3','#'],['4','4','$'],['5','5','%'],['6','6','^'],['7','7','&'],['8','8','*'],['9','9','('],['0','0',')'],['-','-','_'],['=','=','+']],
[['q','q','Q'],['w','w','W'],['e','e','E'],['r','r','R'],['t','t','T'],['y','y','Y'],['u','u','U'],['i','i','I'],['o','o','O'],['p','p','P'],['[','[','{'],[']',']','}'],['\\','\\','|']],
[['a','a','A'],['s','s','S'],['d','d','D'],['f','f','F'],['g','g','G'],['h','h','H'],['j','j','J'],['k','k','K'],['l','l','L'],[';',';',':'],["'","'",'"']],
[['z','z','Z'],['x','x','X'],['c','c','C'],['v','v','V'],['b','b','B'],['n','n','N'],['m','m','M'],[',',',','<'],['.','.','>'],['/','/','?']]
];
function rowsForLanguage(language=typingLanguage){return language==='en'?englishRows:rows}
function mappingsForLanguage(language=typingLanguage){return rowsForLanguage(language).flat().flatMap(([key,normal,shift])=>[{key,value:normal,shift:false},{key,value:shift,shift:true}]).sort((a,b)=>b.value.length-a.value.length)}
const special=[['Backspace','Backspace','⌫'],[' ','Space','Space'],['Enter','Enter','↵ Enter']];
function render(){keyboard.innerHTML='';rowsForLanguage().forEach(row=>{const el=document.createElement('div');el.className='key-row';row.forEach(([latin,normal,shift])=>el.appendChild(makeKey(latin,shifted?shift:normal)));keyboard.appendChild(el)});const bottom=document.createElement('div');bottom.className='key-row';special.forEach(([value,label,display])=>{const b=makeKey(label,display,value);b.classList.add('wide');if(value===' ')b.classList.add('space');bottom.appendChild(b)});keyboard.appendChild(bottom)}
function makeKey(label,char,value=char){const b=document.createElement('button');b.type='button';b.className='key';b.dataset.value=value;b.dataset.code=label;b.innerHTML=`<small>${label==='Space'?'':label}</small>${char}`;b.addEventListener('click',()=>insert(value));return b}
function insert(value){editor.focus();if(value==='Backspace'){document.execCommand('delete');}else if(value==='Enter'){document.execCommand('insertText',false,'\n');}else{document.execCommand('insertText',false,value)}updateCount()}
function updateCount(){const n=[...editor.value].length;count.textContent=`${n} ${n===1?'character':'characters'}`}
function setShift(on){shifted=on;document.querySelector('#normalMode').classList.toggle('active',!on);document.querySelector('#shiftMode').classList.toggle('active',on);render()}
document.querySelector('#normalMode').onclick=()=>setShift(false);document.querySelector('#shiftMode').onclick=()=>setShift(true);
function physicalKey(e){if(e.code.startsWith('Key'))return e.code.slice(3).toLowerCase();if(e.code.startsWith('Digit'))return e.code.slice(5);return({Backquote:'`',Minus:'-',Equal:'=',BracketLeft:'[',BracketRight:']',Backslash:'\\',Semicolon:';',Quote:"'",Comma:',',Period:'.',Slash:'/'}[e.code]||e.key.toLowerCase())}
editor.addEventListener('input',updateCount);editor.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Shift'){setShift(true);return}const key=physicalKey(e),match=rowsForLanguage().flat().find(([mapped])=>mapped===key);if(match){if(typingLanguage==='ksw'){e.preventDefault();insert(e.shiftKey?match[2]:match[1])}flashKey(match[0])}});editor.addEventListener('keyup',e=>{if(e.key==='Shift')setShift(false)});
function flashKey(code){const b=[...document.querySelectorAll('.key')].find(k=>k.dataset.code===code);if(b){b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),110)}}
document.querySelector('#copy').onclick=async()=>{if(!editor.value){showToast('Type something first');return}try{await navigator.clipboard.writeText(editor.value)}catch{editor.select();document.execCommand('copy')}document.querySelector('#copyText').textContent='Copied';showToast('Copied to clipboard');setTimeout(()=>document.querySelector('#copyText').textContent='Copy text',1400)};
document.querySelector('#clear').onclick=()=>{if(!editor.value)return;editor.value='';updateCount();editor.focus();showToast('Text cleared')};document.querySelector('#selectAll').onclick=()=>{editor.focus();editor.select()};document.querySelector('#undo').onclick=()=>{editor.focus();document.execCommand('undo');updateCount()};document.querySelector('#toggleGuide').onclick=()=>{const g=document.querySelector('#guide');g.hidden=!g.hidden};
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
function updateLanguageInterface(){const english=typingLanguage==='en';document.querySelector('#languageKaren').classList.toggle('active',!english);document.querySelector('#languageEnglish').classList.toggle('active',english);document.querySelector('#typeEyebrow').textContent=english?'ENGLISH · QWERTY':'S’GAW KAREN · ကညီကျိာ်';document.querySelector('#editor-title').textContent=english?'Type in English':'Type in Karen';document.querySelector('#typeHint').textContent=english?'Standard QWERTY layout — use your keyboard or tap below.':'KarenKNU layout — use your English keyboard or tap below.';document.querySelector('#guide').textContent=english?'This is the standard English QWERTY layout. Press Shift for capital letters and symbols.':'This is the KarenKNU S’gaw Karen layout. Each key shows its English shortcut. Press Shift for the second layer.';document.querySelector('#gamesEyebrow').textContent=english?'ENGLISH TYPING GAMES':'KAREN TYPING GAMES';document.querySelector('#gamesHint').textContent=english?'Practice English words while building speed and accuracy.':'Practice Karen words while building speed and accuracy.';document.querySelector('#practiceEyebrow').textContent=english?'ENGLISH TYPING PRACTICE':'KAREN TYPING PRACTICE';document.querySelector('[data-game="sprint"] small').textContent=english?'Type as many English words as you can in 45 seconds.':'Type as many Karen words as you can in 45 seconds.';document.querySelector('[data-game="rain"] small').textContent=english?'Type each English word before it reaches the bottom.':'Type each Karen word before it reaches the bottom.';editor.lang=english?'en':'ksw';editor.placeholder=english?'Type here…':'တီၢ်လံာ်ဖဲအံၤ…';setShift(false);render()}
function setTypingLanguage(language){typingLanguage=language==='en'?'en':'ksw';localStorage.setItem('typingLanguage',typingLanguage);updateLanguageInterface();window.dispatchEvent(new CustomEvent('typinglanguagechange',{detail:{language:typingLanguage}}));if(!document.querySelector('#typeView').hidden)editor.focus()}
document.querySelector('#languageKaren').onclick=()=>setTypingLanguage('ksw');document.querySelector('#languageEnglish').onclick=()=>setTypingLanguage('en');updateLanguageInterface();updateCount();
