const customStage=document.querySelector('#customGameStage'),customSetup=document.querySelector('#customGameSetup'),customLive=document.querySelector('#customGameLive'),customResults=document.querySelector('#customGameResults');
const customListKey='glnCustomGameListsV1';const cq=s=>document.querySelector(s);
const defenseAvatars=['🧙','🦸','🥷','🤖','🧑‍🚀','🧑‍🚒','🧚','🐉','🦊','🐼','🦁','🐯'];
const DEFENSE_CODE_CHARS='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
let customMode='adventure',customItems=[],customIndex=0,customScore=0,customLives=3,customValue='',customDeadline=0,customFrame=null,customDifficultyMode='normal',customLanguage=typingLanguage;
let defenseCode='',defenseRole='',defensePlayerId='',defensePlayerName='',defenseAvatarIndex=0,defenseRoom=null,defenseUnsubscribe=null,defenseClassStarted=false,defenseFinishing=false;
function customLists(){try{return JSON.parse(localStorage.getItem(customListKey)||'{}')}catch{return{}}}
function writeCustomLists(v){localStorage.setItem(customListKey,JSON.stringify(v))}
function parseCustomItems(value){return String(value||'').split(/\r?\n|,/).map(v=>v.trim().replace(/\s+/g,' ')).filter(Boolean)}
function refreshCustomLists(){const menu=cq('#customSavedList'),current=menu.value,lists=customLists();menu.innerHTML='<option value="">Choose a saved list…</option>';Object.keys(lists).sort().forEach(name=>menu.add(new Option(name,name)));if(lists[current])menu.value=current}
function languageTagFor(language){return language==='en'?'en':language==='pwo'?'kjp':'ksw'}
function customGameLanguage(){return customMode==='defense'&&defenseRole==='player'?customLanguage:typingLanguage}
function customDifficulty(){return customMode==='defense'&&defenseRole==='player'?customDifficultyMode:cq('#customDifficulty').value}
function difficultySeconds(){return customDifficulty()==='easy'?15:customDifficulty()==='hard'?7:10}
function shuffledChallenges(source,count){const items=Array.from({length:count},(_,i)=>source[i%source.length]);for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items}
function defenseRoomRef(code){return fb.ref(db,`defenseRooms/${code}`)}
function defensePlayerRef(code,uid){return fb.ref(db,`defenseRooms/${code}/players/${uid}`)}
function makeDefenseCode(){return Array.from({length:5},()=>DEFENSE_CODE_CHARS[Math.floor(Math.random()*DEFENSE_CODE_CHARS.length)]).join('')}
function defenseError(message){cq('#defenseClassError').textContent=message||''}
function renderDefenseAvatarPicker(){const box=cq('#defenseAvatarPicker');box.innerHTML='';defenseAvatars.forEach((avatar,index)=>{const button=document.createElement('button');button.type='button';button.className='defense-avatar-choice';button.textContent=avatar;button.setAttribute('role','radio');button.setAttribute('aria-label',`Defender ${index+1}`);button.onclick=()=>{defenseAvatarIndex=index;renderDefenseAvatarPicker()};const selected=index===defenseAvatarIndex;button.classList.toggle('selected',selected);button.setAttribute('aria-checked',selected?'true':'false');box.appendChild(button)})}
function closeDefenseRoom(){if(defenseUnsubscribe){defenseUnsubscribe();defenseUnsubscribe=null}defenseRoom=null;defenseClassStarted=false;defenseFinishing=false;defenseCode='';defenseRole='';defensePlayerId='';defensePlayerName=''}
function openCustomGame(mode){
  stopGame();if(typeof closeRace==='function')closeRace();closeDefenseRoom();customMode=mode;gameGrid.hidden=true;gameStage.hidden=true;const raceStage=cq('#raceStage');if(raceStage)raceStage.hidden=true;customStage.hidden=false;customLive.hidden=true;customResults.hidden=true;cq('#defenseLobby').hidden=true;cq('#defenseTeacherLive').hidden=true;
  const adventure=mode==='adventure';cq('#customGameTitle').textContent=adventure?'Typing Adventure':'Typing Defense';cq('#customGameIcon').textContent=adventure?'🧭':'🛡️';cq('#customRestart').hidden=!adventure;
  if(adventure){
    cq('#defenseClassSetup').hidden=true;customSetup.hidden=false;cq('#customSetupTitle').textContent='Build a Typing Adventure';cq('#customStartGame').textContent='Start adventure';cq('#customWordsInput').lang=languageTag();if(!cq('#customWordsInput').value)cq('#customWordsInput').value=activeGameWords().join('\n');customError('');refreshCustomLists()
  }else{
    customSetup.hidden=true;cq('#defenseClassSetup').hidden=false;defenseError('');cq('#defenseConnection').textContent='Connecting…';cq('#defenseWordsInput').lang=languageTag();if(!cq('#defenseWordsInput').value)cq('#defenseWordsInput').value=activeGameWords().join('\n');cq('#defenseCodeInput').value='';cq('#defenseNameInput').value='';defenseAvatarIndex=0;renderDefenseAvatarPicker();
    initRaceFirebase().then(()=>cq('#defenseConnection').textContent='Online').catch(()=>cq('#defenseConnection').textContent='Offline')
  }
  window.scrollTo({top:0,behavior:'smooth'})
}
document.querySelectorAll('[data-game="adventure"],[data-game="defense"]').forEach(card=>card.onclick=()=>openCustomGame(card.dataset.game));
function resetCustomSetup(){stopCustomGame();customSetup.hidden=false;customLive.hidden=true;customResults.hidden=true}
cq('#customBackGames').onclick=()=>{stopCustomGame();closeDefenseRoom();customStage.hidden=true;gameGrid.hidden=false};
cq('#customRestart').onclick=resetCustomSetup;cq('#customNewList').onclick=resetCustomSetup;cq('#customPlayAgain').onclick=()=>beginCustomGame();
cq('#customSavedList').onchange=e=>{const value=customLists()[e.target.value];if(value)cq('#customWordsInput').value=value};
cq('#customSaveList').onclick=()=>{const value=cq('#customWordsInput').value;if(!parseCustomItems(value).length)return customError('Add words or sentences first.');const name=prompt('Name this list:',`Game List ${Object.keys(customLists()).length+1}`);if(!name?.trim())return;const lists=customLists(),clean=name.trim().slice(0,40);lists[clean]=value;writeCustomLists(lists);refreshCustomLists();cq('#customSavedList').value=clean;showToast('Game list saved')};
cq('#customDeleteList').onclick=()=>{const name=cq('#customSavedList').value;if(!name)return;const lists=customLists();delete lists[name];writeCustomLists(lists);refreshCustomLists();showToast('Saved list deleted')};
function customError(message){cq('#customGameError').textContent=message}
cq('#customStartGame').onclick=beginCustomGame;
function beginCustomGame(){const source=parseCustomItems(cq('#customWordsInput').value);if(!source.length)return customError('Add at least one word or sentence.');const count=Math.max(1,Math.min(50,Number(cq('#customChallengeCount').value)||10));customItems=shuffledChallenges(source,count);customIndex=0;customScore=0;customLives=3;customValue='';customLanguage=typingLanguage;customDifficultyMode=cq('#customDifficulty').value;customSetup.hidden=true;customResults.hidden=true;cq('#customResultActions').hidden=false;customLive.hidden=false;cq('#adventureWorld').hidden=customMode!=='adventure';cq('#defenseWorld').hidden=customMode!=='defense';cq('#customStatusLabel').textContent=customMode==='adventure'?'Checkpoint':'Wave';cq('#customLifeLabel').textContent=customMode==='adventure'?'Stars':'Shields';nextCustomChallenge()}
function stopCustomGame(){cancelAnimationFrame(customFrame);customFrame=null}
function nextCustomChallenge(){stopCustomGame();if(customIndex>=customItems.length||customLives<=0)return finishCustomGame();customValue='';cq('#customTyped').textContent='';cq('#customTyped').className='custom-typed';cq('#customRound').textContent=`${customIndex+1} / ${customItems.length}`;cq('#customScore').textContent=customScore;const filled=customMode==='adventure'?'★':'◆',empty=customMode==='adventure'?'☆':'◇';cq('#customLives').textContent=filled.repeat(customLives)+empty.repeat(3-customLives);renderCustomTarget();renderCustomKeyboard();if(customMode==='adventure')cq('#adventurePlayer').style.left=`${(customIndex/customItems.length)*100}%`;else{cq('#defenseEnemy').style.left='0%';customDeadline=performance.now()+difficultySeconds()*1000;customFrame=requestAnimationFrame(animateDefense)}}
function renderCustomTarget(){const target=customItems[customIndex],box=cq('#customTarget'),done=document.createElement('span'),current=document.createElement('span');done.className='done';done.textContent=target.slice(0,customValue.length);current.className='current';current.textContent=target.slice(customValue.length,customValue.length+1)||' ';box.replaceChildren(done,current,document.createTextNode(target.slice(customValue.length+1)))}
function customExpected(){const target=customItems[customIndex]||'';if(target[customValue.length]===' ')return{key:'Space',value:' ',shift:false};return mappingsForLanguage(customGameLanguage()).find(m=>target.startsWith(m.value,customValue.length))||null}
function customControl(label,action,active=false){const b=document.createElement('button');b.type='button';b.className='key wide game-control';b.textContent=label;b.onclick=action;if(active)b.classList.add('shift-required');return b}
function renderCustomKeyboard(){const box=cq('#customGameKeyboard');box.innerHTML='';const expected=customExpected(),needShift=expected?.shift||false;if(customDifficulty()==='hard'){box.hidden=true;return}box.hidden=false;rowsForLanguage(customGameLanguage()).forEach((row,rowIndex)=>{const line=document.createElement('div');line.className='key-row';row.forEach(([key,normal,shift])=>{const b=document.createElement('button');b.type='button';b.className='key';b.dataset.code=key;b.innerHTML=`<small>${key}</small>${needShift?shift:normal}`;if(expected?.key===key)b.classList.add('expected');b.onclick=()=>acceptCustomInput(needShift?shift:normal);line.appendChild(b)});if(rowIndex===0)line.appendChild(customControl('Backspace',customBackspace));box.appendChild(line)});const bottom=document.createElement('div');bottom.className='key-row';bottom.appendChild(customControl('Shift',()=>{},needShift));const space=customControl('Space',()=>acceptCustomInput(' '));space.classList.add('space');if(expected?.key==='Space')space.classList.add('expected');bottom.append(space,customControl('Shift',()=>{},needShift));box.appendChild(bottom)}
function customBackspace(){if(!customValue)return;customValue=customValue.slice(0,previousTextBoundary(customValue,customValue.length));cq('#customTyped').textContent=customValue;renderCustomTarget();renderCustomKeyboard()}
function syncDefensePlayer(finished=false){if(defenseRole!=='player'||!defenseCode||!defensePlayerId||!fb)return Promise.resolve();return fb.update(defensePlayerRef(defenseCode,defensePlayerId),{score:customScore,index:customIndex,lives:customLives,finished:!!finished,finishedAt:finished?Date.now():0}).catch(()=>{})}
function acceptCustomInput(value){if(customLive.hidden||!customItems[customIndex])return;const remaining=customItems[customIndex].slice(customValue.length);if(remaining.startsWith(value)){customValue+=value;cq('#customTyped').textContent=customValue;renderCustomTarget();if(customValue===customItems[customIndex]){customScore++;customIndex++;if(defenseRole==='player'&&customMode==='defense')syncDefensePlayer(customIndex>=customItems.length);nextCustomChallenge()}else renderCustomKeyboard()}else{cq('#customTyped').classList.add('wrong');setTimeout(()=>cq('#customTyped').classList.remove('wrong'),220);if(customMode==='adventure'&&customDifficulty()==='hard'){customLives--;nextCustomChallenge()}}}
function animateDefense(now){if(customMode!=='defense'||customLive.hidden)return;const progress=Math.min(1,1-(customDeadline-now)/(difficultySeconds()*1000));cq('#defenseEnemy').style.left=`${progress*82}%`;cq('#defenseTimerBar').style.transform=`scaleX(${1-progress})`;if(progress>=1){customLives--;customIndex++;if(defenseRole==='player')syncDefensePlayer(customIndex>=customItems.length||customLives<=0);nextCustomChallenge();return}customFrame=requestAnimationFrame(animateDefense)}
function finishCustomGame(){stopCustomGame();customLive.hidden=true;customResults.hidden=false;const win=customLives>0;cq('#customResultIcon').textContent=win?'🏆':'🎯';if(defenseRole==='player'&&customMode==='defense'){syncDefensePlayer(true);cq('#customResultTitle').textContent=win?'Village protected!':'Defense complete';cq('#customResultSummary').textContent=`You completed ${customScore} of ${customItems.length} challenges. Waiting for the class to finish.`;cq('#customResultActions').hidden=true;return}cq('#customResultTitle').textContent=customMode==='adventure'?(win?'Adventure complete!':'Adventure ended'):(win?'Village protected!':'Defense complete');cq('#customResultSummary').textContent=`You completed ${customScore} of ${customItems.length} challenges.`;cq('#customResultActions').hidden=false;const key=`glnBest_${typingLanguage}_${customMode}`;localStorage.setItem(key,Math.max(customScore,Number(localStorage.getItem(key)||0)))}

cq('#defenseCreateForm').onsubmit=async event=>{event.preventDefault();defenseError('');const source=parseCustomItems(cq('#defenseWordsInput').value),count=Math.max(1,Math.min(50,Number(cq('#defenseChallengeCount').value)||10));try{if(!source.length)throw new Error('Paste at least one word or sentence.');await initRaceFirebase();let created=false,tries=0;while(!created&&tries<10){tries++;const code=makeDefenseCode(),ref=defenseRoomRef(code),existing=await fb.get(ref);if(existing.exists())continue;const now=Date.now(),items=shuffledChallenges(source,count);await fb.set(ref,{hostUid:currentUser.uid,items,difficulty:cq('#defenseDifficulty').value,challengeCount:items.length,language:typingLanguage,status:'waiting',createdAt:now,expiresAt:now+14400000,startedAt:0,players:{}});defenseCode=code;created=true}if(!created)throw new Error('Could not create a room. Please try again.');defenseRole='host';defensePlayerId='';showDefenseLobby({players:[]});watchDefenseRoom()}catch(error){defenseError(error.message||'Could not create the defense room.')}};
cq('#defenseJoinForm').onsubmit=async event=>{event.preventDefault();defenseError('');const code=cq('#defenseCodeInput').value.trim().toUpperCase(),name=cleanName(cq('#defenseNameInput').value);try{if(!/^[A-Z2-9]{5}$/.test(code))throw new Error('Enter a valid five-character room code.');if(!name)throw new Error('Enter your name.');await initRaceFirebase();const snap=await fb.get(defenseRoomRef(code));if(!snap.exists())throw new Error('Defense room not found. Check the code.');const room=snap.val();if(room.expiresAt&&room.expiresAt<Date.now())throw new Error('This defense room has expired.');if(room.status!=='waiting')throw new Error('This defense game has already started.');const players=Object.values(room.players||{});if(players.length>=40)throw new Error('This room is full.');if(players.some(player=>String(player.name||'').toLowerCase()===name.toLowerCase()))throw new Error('That name is already in this room. Add an initial.');defenseCode=code;defenseRole='player';defensePlayerId=currentUser.uid;defensePlayerName=name;customLanguage=room.language||typingLanguage;const player={id:currentUser.uid,name,avatar:defenseAvatarIndex,score:0,index:0,lives:3,finished:false,joinedAt:Date.now(),finishedAt:0};await fb.set(defensePlayerRef(code,currentUser.uid),player);showDefenseLobby({players:[...players,player]});watchDefenseRoom()}catch(error){defenseError(error.message||'Could not join the defense room.')}};
function showDefenseLobby(data){cq('#defenseClassSetup').hidden=true;customSetup.hidden=true;customLive.hidden=true;customResults.hidden=true;cq('#defenseTeacherLive').hidden=true;cq('#defenseLobby').hidden=false;cq('#defenseRoomCode').textContent=defenseCode;const host=defenseRole==='host';cq('#startDefenseRoom').hidden=!host;cq('#defenseLobbyTitle').textContent=host?'Waiting for defenders':'You joined the defense!';cq('#defenseLobbyHint').textContent=host?'Share the room code. Start when everyone has joined.':'Your avatar is ready. Wait for the host to start.';renderDefenseLobbyPlayers(data.players||[])}
function renderDefenseLobbyPlayers(players){const box=cq('#defenseLobbyPlayers');box.innerHTML='';cq('#defensePlayerCount').textContent=`Joined: ${players.length} ${players.length===1?'player':'players'}`;cq('#startDefenseRoom').disabled=defenseRole==='host'&&!players.length;if(!players.length){box.innerHTML='<span class="defense-empty-player">No players yet</span>';return}players.sort((a,b)=>(a.joinedAt||0)-(b.joinedAt||0)).forEach(player=>{const chip=document.createElement('span');chip.className='defense-player-chip';const avatar=document.createElement('b');avatar.textContent=defenseAvatars[player.avatar||0]||defenseAvatars[0];const name=document.createElement('span');name.textContent=player.name;chip.append(avatar,name);if(defenseRole==='host'){const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.title=`Remove ${player.name}`;remove.onclick=()=>fb.remove(defensePlayerRef(defenseCode,player.id)).catch(()=>{});chip.appendChild(remove)}box.appendChild(chip)})}
cq('#copyDefenseCode').onclick=async()=>{try{await navigator.clipboard.writeText(defenseCode);showToast('Defense code copied')}catch{showToast(`Defense code: ${defenseCode}`)}};
cq('#startDefenseRoom').onclick=async()=>{try{if(defenseRole!=='host')return;const snap=await fb.get(defenseRoomRef(defenseCode));if(!snap.exists())throw new Error('Room not found.');const room=snap.val();if(room.hostUid!==currentUser.uid)throw new Error('Only the host can start this game.');if(!Object.keys(room.players||{}).length)throw new Error('Wait for at least one player to join.');await fb.update(defenseRoomRef(defenseCode),{status:'playing',startedAt:Date.now()})}catch(error){cq('#defenseLobbyHint').textContent=error.message}};
function watchDefenseRoom(){if(defenseUnsubscribe)defenseUnsubscribe();defenseUnsubscribe=fb.onValue(defenseRoomRef(defenseCode),snap=>{if(!snap.exists()){defenseError('This defense room is no longer available.');return}defenseRoom=snap.val();cq('#defenseConnection').textContent='Online';const players=Object.values(defenseRoom.players||{});if(defenseRoom.status==='waiting'){defenseClassStarted=false;showDefenseLobby({players});return}if(defenseRoom.status==='playing'){if(defenseRole==='host'){renderDefenseTeacherLive(defenseRoom,players);if(players.length&&players.every(player=>player.finished)&&!defenseFinishing){defenseFinishing=true;fb.update(defenseRoomRef(defenseCode),{status:'finished'}).finally(()=>defenseFinishing=false)}}else if(defenseRole==='player'&&!defenseClassStarted){beginDefensePlayer(defenseRoom)}return}if(defenseRoom.status==='finished'){if(defenseRole==='host')renderDefenseTeacherResults(defenseRoom,players);else renderDefensePlayerFinished(defenseRoom)}} ,()=>cq('#defenseConnection').textContent='Reconnecting…')}
function beginDefensePlayer(room){const me=room.players?.[defensePlayerId];if(!me)return;defenseClassStarted=true;customMode='defense';customItems=Array.isArray(room.items)?room.items:Object.values(room.items||{});customIndex=Math.max(0,Math.min(customItems.length,Number(me.index)||0));customScore=Number(me.score)||0;customLives=Math.max(0,Math.min(3,Number(me.lives??3)));customValue='';customLanguage=room.language||typingLanguage;customDifficultyMode=room.difficulty||'normal';cq('#defenseLobby').hidden=true;cq('#defenseClassSetup').hidden=true;cq('#defenseTeacherLive').hidden=true;customResults.hidden=true;cq('#customResultActions').hidden=true;customLive.hidden=false;cq('#adventureWorld').hidden=true;cq('#defenseWorld').hidden=false;cq('#customStatusLabel').textContent='Wave';cq('#customLifeLabel').textContent='Shields';cq('#customTarget').lang=languageTagFor(customLanguage);cq('#customTyped').lang=languageTagFor(customLanguage);cq('#defensePlayerAvatar').textContent=defenseAvatars[me.avatar||0]||defenseAvatars[0];nextCustomChallenge()}
function defenseProgressText(player,total){if(player.finished)return 'Finished';const current=Math.min(total,Math.max(0,Number(player.index)||0)+1);return `Wave ${current} / ${total}`}
function renderDefenseScoreboard(players,total){const board=cq('#defenseScoreboard');board.innerHTML='';const sorted=[...players].sort((a,b)=>(b.score||0)-(a.score||0)||((b.lives||0)-(a.lives||0))||((a.joinedAt||0)-(b.joinedAt||0)));if(!sorted.length){board.innerHTML='<div class="defense-score-empty">No players in this room.</div>';return}sorted.forEach((player,index)=>{const card=document.createElement('article');card.className='defense-score-card';const avatar=document.createElement('span');avatar.className='defense-score-avatar';avatar.textContent=defenseAvatars[player.avatar||0]||defenseAvatars[0];const info=document.createElement('div');const name=document.createElement('strong');name.textContent=`${index+1}. ${player.name}`;const progress=document.createElement('span');progress.textContent=defenseProgressText(player,total);info.append(name,progress);const meter=document.createElement('div');meter.className='defense-score-meter';const bar=document.createElement('span');bar.style.width=`${Math.min(100,(Number(player.index)||0)/Math.max(1,total)*100)}%`;meter.appendChild(bar);const stats=document.createElement('div');stats.className='defense-score-stats';const score=document.createElement('b');score.textContent=`${player.score||0} pts`;const lives=document.createElement('span');lives.textContent=`${'◆'.repeat(Math.max(0,player.lives??3))}${'◇'.repeat(Math.max(0,3-(player.lives??3)))}`;stats.append(score,lives);card.append(avatar,info,meter,stats);if(player.finished)card.classList.add('finished');board.appendChild(card)})}
function renderDefenseTeacherLive(room,players){stopCustomGame();cq('#defenseClassSetup').hidden=true;cq('#defenseLobby').hidden=true;customLive.hidden=true;customResults.hidden=true;cq('#defenseTeacherLive').hidden=false;cq('#defenseTeacherResults').hidden=true;cq('#endDefenseRoom').hidden=false;cq('#defenseLiveCode').textContent=defenseCode;renderDefenseScoreboard(players,room.challengeCount||room.items?.length||0)}
function renderDefenseTeacherResults(room,players){stopCustomGame();cq('#defenseClassSetup').hidden=true;cq('#defenseLobby').hidden=true;customLive.hidden=true;customResults.hidden=true;cq('#defenseTeacherLive').hidden=false;cq('#endDefenseRoom').hidden=true;cq('#defenseTeacherResults').hidden=false;cq('#defenseLiveCode').textContent=defenseCode;renderDefenseScoreboard(players,room.challengeCount||room.items?.length||0);const top=[...players].sort((a,b)=>(b.score||0)-(a.score||0))[0];cq('#defenseTeacherSummary').textContent=top?`${top.name} led the defense with ${top.score||0} points. ${players.length} player${players.length===1?'':'s'} participated.`:'The defense room ended.'}
function renderDefensePlayerFinished(room){stopCustomGame();customLive.hidden=true;cq('#defenseLobby').hidden=true;cq('#defenseTeacherLive').hidden=true;customResults.hidden=false;cq('#customResultActions').hidden=true;const me=room.players?.[defensePlayerId],score=me?.score??customScore,total=room.challengeCount||customItems.length,lives=me?.lives??customLives;cq('#customResultIcon').textContent=lives>0?'🏆':'🎯';cq('#customResultTitle').textContent='Class defense complete!';cq('#customResultSummary').textContent=`You completed ${score} of ${total} challenges.`}
cq('#endDefenseRoom').onclick=()=>{if(defenseRole==='host'&&defenseCode)fb.update(defenseRoomRef(defenseCode),{status:'finished'}).catch(()=>{})};
cq('#defensePlayAgain').onclick=async()=>{if(defenseRole!=='host'||!defenseRoom)return;const updates={status:'waiting',startedAt:0};Object.keys(defenseRoom.players||{}).forEach(uid=>{updates[`players/${uid}/score`]=0;updates[`players/${uid}/index`]=0;updates[`players/${uid}/lives`]=3;updates[`players/${uid}/finished`]=false;updates[`players/${uid}/finishedAt`]=0});await fb.update(defenseRoomRef(defenseCode),updates).catch(error=>defenseError(error.message))};
cq('#defenseNewRoom').onclick=()=>{closeDefenseRoom();openCustomGame('defense')};

document.addEventListener('keydown',e=>{if(customStage.hidden||customLive.hidden||e.ctrlKey||e.metaKey||e.altKey||e.key==='Shift')return;const key=physicalKey(e);if(key==='Backspace'){e.preventDefault();customBackspace();return}const match=rowsForLanguage(customGameLanguage()).flat().find(([mapped])=>mapped===key);if(match){e.preventDefault();acceptCustomInput(e.shiftKey?match[2]:match[1])}else if(e.key===' '){e.preventDefault();acceptCustomInput(' ')}});
window.addEventListener('typinglanguagechange',()=>{cq('#customWordsInput').lang=languageTag();cq('#defenseWordsInput').lang=languageTag();if(!(customMode==='defense'&&defenseRole==='player')){cq('#customTarget').lang=languageTag();cq('#customTyped').lang=languageTag()}});
