const customStage=document.querySelector('#customGameStage'),customSetup=document.querySelector('#customGameSetup'),customLive=document.querySelector('#customGameLive'),customResults=document.querySelector('#customGameResults');
const customListKey='glnCustomGameListsV1';let customMode='adventure',customItems=[],customIndex=0,customScore=0,customLives=3,customValue='',customDeadline=0,customFrame=null;const cq=s=>document.querySelector(s);
function customLists(){try{return JSON.parse(localStorage.getItem(customListKey)||'{}')}catch{return{}}}function writeCustomLists(v){localStorage.setItem(customListKey,JSON.stringify(v))}function parseCustomItems(value){return value.split(/\r?\n|,/).map(v=>v.trim().replace(/\s+/g,' ')).filter(Boolean)}
function refreshCustomLists(){const menu=cq('#customSavedList'),current=menu.value,lists=customLists();menu.innerHTML='<option value="">Choose a saved list…</option>';Object.keys(lists).sort().forEach(name=>menu.add(new Option(name,name)));if(lists[current])menu.value=current}
function openCustomGame(mode){stopGame();if(typeof closeRace==='function')closeRace();customMode=mode;gameGrid.hidden=true;gameStage.hidden=true;const raceStage=cq('#raceStage');if(raceStage)raceStage.hidden=true;customStage.hidden=false;customSetup.hidden=false;customLive.hidden=true;customResults.hidden=true;const adventure=mode==='adventure';cq('#customGameTitle').textContent=adventure?'Typing Adventure':'Typing Defense';cq('#customGameIcon').textContent=adventure?'🧭':'🛡️';cq('#customSetupTitle').textContent=adventure?'Build a Typing Adventure':'Build a Typing Defense Game';cq('#customStartGame').textContent=adventure?'Start adventure':'Start defense';cq('#customWordsInput').lang=languageTag();if(!cq('#customWordsInput').value)cq('#customWordsInput').value=activeGameWords().join('\n');customError('');refreshCustomLists();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-game="adventure"],[data-game="defense"]').forEach(card=>card.onclick=()=>openCustomGame(card.dataset.game));
function resetCustomSetup(){stopCustomGame();customSetup.hidden=false;customLive.hidden=true;customResults.hidden=true}cq('#customBackGames').onclick=()=>{stopCustomGame();customStage.hidden=true;gameGrid.hidden=false};cq('#customRestart').onclick=resetCustomSetup;cq('#customNewList').onclick=resetCustomSetup;cq('#customPlayAgain').onclick=()=>beginCustomGame();
cq('#customSavedList').onchange=e=>{const value=customLists()[e.target.value];if(value)cq('#customWordsInput').value=value};cq('#customSaveList').onclick=()=>{const value=cq('#customWordsInput').value;if(!parseCustomItems(value).length)return customError('Add words or sentences first.');const name=prompt('Name this list:',`Game List ${Object.keys(customLists()).length+1}`);if(!name?.trim())return;const lists=customLists(),clean=name.trim().slice(0,40);lists[clean]=value;writeCustomLists(lists);refreshCustomLists();cq('#customSavedList').value=clean;showToast('Game list saved')};cq('#customDeleteList').onclick=()=>{const name=cq('#customSavedList').value;if(!name)return;const lists=customLists();delete lists[name];writeCustomLists(lists);refreshCustomLists();showToast('Saved list deleted')};function customError(message){cq('#customGameError').textContent=message}cq('#customStartGame').onclick=beginCustomGame;
function beginCustomGame(){const source=parseCustomItems(cq('#customWordsInput').value);if(!source.length)return customError('Add at least one word or sentence.');const count=Math.max(1,Math.min(50,Number(cq('#customChallengeCount').value)||10));customItems=Array.from({length:count},(_,i)=>source[i%source.length]).sort(()=>Math.random()-.5);customIndex=0;customScore=0;customLives=3;customValue='';customSetup.hidden=true;customResults.hidden=true;customLive.hidden=false;cq('#adventureWorld').hidden=customMode!=='adventure';cq('#defenseWorld').hidden=customMode!=='defense';cq('#customStatusLabel').textContent=customMode==='adventure'?'Checkpoint':'Wave';cq('#customLifeLabel').textContent=customMode==='adventure'?'Stars':'Shields';nextCustomChallenge()}
function difficultySeconds(){return cq('#customDifficulty').value==='easy'?15:cq('#customDifficulty').value==='hard'?7:10}function stopCustomGame(){cancelAnimationFrame(customFrame);customFrame=null}
function nextCustomChallenge(){stopCustomGame();if(customIndex>=customItems.length||customLives<=0)return finishCustomGame();customValue='';cq('#customTyped').textContent='';cq('#customTyped').className='custom-typed';cq('#customRound').textContent=`${customIndex+1} / ${customItems.length}`;cq('#customScore').textContent=customScore;const filled=customMode==='adventure'?'★':'◆',empty=customMode==='adventure'?'☆':'◇';cq('#customLives').textContent=filled.repeat(customLives)+empty.repeat(3-customLives);renderCustomTarget();renderCustomKeyboard();if(customMode==='adventure')cq('#adventurePlayer').style.left=`${(customIndex/customItems.length)*100}%`;else{customDeadline=performance.now()+difficultySeconds()*1000;customFrame=requestAnimationFrame(animateDefense)}}
function renderCustomTarget(){const target=customItems[customIndex],box=cq('#customTarget'),done=document.createElement('span'),current=document.createElement('span');done.className='done';done.textContent=target.slice(0,customValue.length);current.className='current';current.textContent=target.slice(customValue.length,customValue.length+1)||' ';box.replaceChildren(done,current,document.createTextNode(target.slice(customValue.length+1)))}
function customExpected(){return allMappings().find(m=>customItems[customIndex]?.startsWith(m.value,customValue.length))||null}function customControl(label,action,active=false){const b=document.createElement('button');b.type='button';b.className='key wide game-control';b.textContent=label;b.onclick=action;if(active)b.classList.add('shift-required');return b}
function renderCustomKeyboard(){const box=cq('#customGameKeyboard');box.innerHTML='';const expected=customExpected(),needShift=expected?.shift||false;if(cq('#customDifficulty').value==='hard'){box.hidden=true;return}box.hidden=false;rowsForLanguage().forEach((row,rowIndex)=>{const line=document.createElement('div');line.className='key-row';row.forEach(([key,normal,shift])=>{const b=document.createElement('button');b.type='button';b.className='key';b.dataset.code=key;b.innerHTML=`<small>${key}</small>${needShift?shift:normal}`;if(expected?.key===key)b.classList.add('expected');b.onclick=()=>acceptCustomInput(needShift?shift:normal);line.appendChild(b)});if(rowIndex===0)line.appendChild(customControl('Backspace',customBackspace));box.appendChild(line)});const bottom=document.createElement('div');bottom.className='key-row';bottom.appendChild(customControl('Shift',()=>{},needShift));const space=customControl('Space',()=>acceptCustomInput(' '));space.classList.add('space');if(expected?.key==='Space')space.classList.add('expected');bottom.append(space,customControl('Shift',()=>{},needShift));box.appendChild(bottom)}
function customBackspace(){if(!customValue)return;customValue=customValue.slice(0,previousTextBoundary(customValue,customValue.length));cq('#customTyped').textContent=customValue;renderCustomTarget();renderCustomKeyboard()}
function acceptCustomInput(value){if(customLive.hidden||!customItems[customIndex])return;const remaining=customItems[customIndex].slice(customValue.length);if(remaining.startsWith(value)){customValue+=value;cq('#customTyped').textContent=customValue;renderCustomTarget();if(customValue===customItems[customIndex]){customScore++;customIndex++;nextCustomChallenge()}else renderCustomKeyboard()}else{cq('#customTyped').classList.add('wrong');setTimeout(()=>cq('#customTyped').classList.remove('wrong'),220);if(customMode==='adventure'&&cq('#customDifficulty').value==='hard'){customLives--;nextCustomChallenge()}}}
function animateDefense(now){if(customMode!=='defense'||customLive.hidden)return;const progress=Math.min(1,1-(customDeadline-now)/(difficultySeconds()*1000));cq('#defenseEnemy').style.left=`${progress*82}%`;cq('#defenseTimerBar').style.transform=`scaleX(${1-progress})`;if(progress>=1){customLives--;customIndex++;nextCustomChallenge();return}customFrame=requestAnimationFrame(animateDefense)}
function finishCustomGame(){stopCustomGame();customLive.hidden=true;customResults.hidden=false;const win=customLives>0;cq('#customResultIcon').textContent=win?'🏆':'🎯';cq('#customResultTitle').textContent=customMode==='adventure'?(win?'Adventure complete!':'Adventure ended'):(win?'Village protected!':'Defense complete');cq('#customResultSummary').textContent=`You completed ${customScore} of ${customItems.length} challenges.`;const key=`glnBest_${typingLanguage}_${customMode}`;localStorage.setItem(key,Math.max(customScore,Number(localStorage.getItem(key)||0)))}
document.addEventListener('keydown',e=>{if(customStage.hidden||customLive.hidden||e.ctrlKey||e.metaKey||e.altKey||e.key==='Shift')return;const key=physicalKey(e);if(key==='Backspace'){e.preventDefault();customBackspace();return}const match=rowsForLanguage().flat().find(([mapped])=>mapped===key);if(match){e.preventDefault();acceptCustomInput(e.shiftKey?match[2]:match[1])}else if(e.key===' '){e.preventDefault();acceptCustomInput(' ')}});window.addEventListener('typinglanguagechange',()=>{cq('#customWordsInput').lang=languageTag();cq('#customTarget').lang=languageTag();cq('#customTyped').lang=languageTag()});
