const navGames=document.querySelector('#navGames'),gamesView=document.querySelector('#gamesView'),gameGrid=document.querySelector('#gameGrid'),gameStage=document.querySelector('#gameStage');
const karenGameWords=['မိၢ်','ပၢ်','မိၢ်ပၢ်','ဖိခွါ','ဖိမုၣ်','ဟံၣ်ဖိဃီဖိ','တၢ်အီၣ်','မ့ၤ','ညၣ်','ဆီညၣ်','မုၢ်ဒဲး','မုၢ်ဆၣ်','မုၢ်ယူာ်','ကိးနံၤဒဲး','ကိးဂီၤဒဲး','ကိးဟါဒဲး'];
const englishGameWords=['family','mother','father','student','teacher','school','class','book','pencil','folder','Monday','Friday','practice','typing','English','Karen'];
const pwoGameWords=['ဆ','တ','န','မ','အ','ပ','က','င','သ','စ','ဟ','ဖ','ထ','ခ','လ','ဘ','ည','ဇ','ဝ','ဥ','ဏ'];
function activeGameWords(){return typingLanguage==='en'?englishGameWords:typingLanguage==='pwo'?pwoGameWords:karenGameWords}
let activeGame='',gameRunning=false,gameScore=0,gameStreak=0,gameSeconds=45,gameTarget='',gameBuffer='',gameTimer=null,fallFrame=null,fallStart=0,fallDuration=8000,matchRounds=0,matchTarget=null,lastWord='';
function openGames(){typeView.hidden=true;practiceView.hidden=true;gamesView.hidden=false;navType.classList.remove('active');navPractice.classList.remove('active');navGames.classList.add('active');stopGame();if(typeof closeRace==='function')closeRace();gameGrid.hidden=false;gameStage.hidden=true;window.scrollTo({top:0,behavior:'smooth'})}
navGames.onclick=openGames;
function chooseGame(name){if(name==='race'){openRace();return}activeGame=name;gameGrid.hidden=true;gameStage.hidden=false;const titles={sprint:'Word Sprint',rain:'Falling Words'};document.querySelector('#activeGameTitle').textContent=titles[name];resetGame()}
gameGrid.querySelectorAll('[data-game]').forEach(card=>card.onclick=()=>chooseGame(card.dataset.game));document.querySelector('#backGames').onclick=()=>{stopGame();gameStage.hidden=true;gameGrid.hidden=false};document.querySelector('#restartGame').onclick=resetGame;document.querySelector('#startGame').onclick=startGame;
function resetGame(){stopGame();gameScore=0;gameStreak=0;gameSeconds=activeGame==='sprint'?45:activeGame==='rain'?3:10;matchRounds=0;matchTarget=null;gameBuffer='';updateGameStats();document.querySelector('#gameMessage').hidden=false;document.querySelector('#gameMessage').querySelector('strong').textContent='Ready?';document.querySelector('#gameMessage').querySelector('span').textContent=activeGame==='sprint'?'Type as many words as you can in 45 seconds.':activeGame==='rain'?'You have three lives. Do not let a word fall.':'Match ten Karen characters to their English keys.';document.querySelector('#startGame').textContent='Start game';document.querySelector('#wordChallenge').hidden=true;document.querySelector('#fallingWord').hidden=true;renderGameKeyboard()}
function stopGame(){gameRunning=false;clearInterval(gameTimer);gameTimer=null;cancelAnimationFrame(fallFrame);fallFrame=null}
function startGame(){stopGame();gameRunning=true;document.querySelector('#gameMessage').hidden=true;gameBuffer='';if(activeGame==='sprint'){gameSeconds=45;gameTimer=setInterval(()=>{gameSeconds--;updateGameStats();if(gameSeconds<=0)finishGame('Time is up!')},1000);nextWord()}else if(activeGame==='rain'){gameSeconds=3;nextFallingWord()}else{gameSeconds=10;nextMatch()}}
function randomWord(){const words=activeGameWords();let word;do{word=words[Math.floor(Math.random()*words.length)]}while(word===lastWord&&words.length>1);lastWord=word;return word}
function nextWord(){gameTarget=randomWord();gameBuffer='';document.querySelector('#wordChallenge').hidden=false;document.querySelector('#challengeLabel').textContent='TYPE THIS WORD';document.querySelector('#challengeWord').textContent=gameTarget;document.querySelector('#typedAnswer').textContent='';document.querySelector('#typedAnswer').className='typed-answer';renderGameKeyboard()}
function nextFallingWord(){gameTarget=randomWord();gameBuffer='';const falling=document.querySelector('#fallingWord');falling.textContent=gameTarget;falling.hidden=false;document.querySelector('#wordChallenge').hidden=false;document.querySelector('#challengeLabel').textContent='YOUR TYPING';document.querySelector('#challengeWord').textContent='';document.querySelector('#typedAnswer').textContent='';fallStart=performance.now();fallDuration=Math.max(3800,8000-gameScore*180);cancelAnimationFrame(fallFrame);fallFrame=requestAnimationFrame(animateFall);renderGameKeyboard()}
function animateFall(now){if(!gameRunning||activeGame!=='rain')return;const field=document.querySelector('#playfield'),word=document.querySelector('#fallingWord');const progress=Math.min(1,(now-fallStart)/fallDuration);word.style.top=`${12+progress*(field.clientHeight-word.offsetHeight-24)}px`;if(progress>=1){gameSeconds--;gameStreak=0;updateGameStats();if(gameSeconds<=0){finishGame('No lives left!');return}nextFallingWord();return}fallFrame=requestAnimationFrame(animateFall)}
function matchPool(){return allMappings().filter(item=>item.value&&item.value.length<=2&&(typingLanguage==='en'?/[a-z]/i.test(item.value):/[က-႟]/u.test(item.value)))}
function nextMatch(){if(matchRounds>=10){finishGame('Challenge complete!');return}const pool=matchPool();matchTarget=pool[Math.floor(Math.random()*pool.length)];gameTarget=matchTarget.value;gameBuffer='';document.querySelector('#wordChallenge').hidden=false;document.querySelector('#challengeLabel').textContent='TYPE THE ENGLISH KEY FOR';document.querySelector('#challengeWord').textContent=gameTarget;document.querySelector('#typedAnswer').textContent=matchTarget.shift?'Shift + ?':'?';renderGameKeyboard()}
function gameExpected(){if(activeGame==='match')return matchTarget;return allMappings().find(m=>gameTarget.startsWith(m.value,gameBuffer.length))||null}
function renderGameKeyboard(){const box=document.querySelector('#gameKeyboard');box.innerHTML='';const expected=gameExpected();const shifted=expected?.shift||false;rowsForLanguage().slice(1).forEach(row=>{const line=document.createElement('div');line.className='key-row';row.forEach(([key,normal,shift])=>{const b=document.createElement('button');b.type='button';b.className='key';b.dataset.code=key;b.innerHTML=`<small>${key}</small>${shifted?shift:normal}`;if(activeGame!=='match'&&expected&&expected.key===key)b.classList.add('expected');b.onclick=()=>acceptGameInput(shifted?shift:normal,key,shifted);line.appendChild(b)});box.appendChild(line)});if(activeGame!=='match'){const line=document.createElement('div');line.className='key-row';const b=document.createElement('button');b.type='button';b.className='key wide space';b.textContent='Space';b.onclick=()=>acceptGameInput(' ','Space',false);line.appendChild(b);box.appendChild(line)}}
function acceptGameInput(value,key,shifted){if(!gameRunning)return;if(activeGame==='match'){const valid=matchPool().some(item=>item.value===gameTarget&&item.key===key&&item.shift===shifted&&item.shift===matchTarget.shift);if(valid){gameScore++;gameStreak++;matchRounds++;gameSeconds=10-matchRounds;updateGameStats();nextMatch()}else{gameStreak=0;updateGameStats();flashWrong()}return}const next=gameTarget.slice(gameBuffer.length);if(next.startsWith(value)){gameBuffer+=value;document.querySelector('#typedAnswer').textContent=gameBuffer;document.querySelector('#typedAnswer').className='typed-answer';if(gameBuffer===gameTarget){gameScore++;gameStreak++;updateGameStats();if(activeGame==='rain'){cancelAnimationFrame(fallFrame);nextFallingWord()}else nextWord()}else renderGameKeyboard()}else{gameStreak=0;updateGameStats();flashWrong()}}
function flashWrong(){const answer=document.querySelector('#typedAnswer');answer.classList.add('wrong');setTimeout(()=>answer.classList.remove('wrong'),220)}
function updateGameStats(){document.querySelector('#gameScore').textContent=gameScore;document.querySelector('#gameMiddleLabel').textContent=activeGame==='rain'?'Streak':'Streak';document.querySelector('#gameMiddle').textContent=gameStreak;document.querySelector('#gameTimeLabel').textContent=activeGame==='rain'?'Lives':activeGame==='match'?'Rounds left':'Time';document.querySelector('#gameTime').textContent=gameSeconds}
function finishGame(title){stopGame();document.querySelector('#gameMessage').hidden=false;document.querySelector('#gameMessage').querySelector('strong').textContent=title;document.querySelector('#gameMessage').querySelector('span').textContent=`Final score: ${gameScore}`;document.querySelector('#startGame').textContent='Play again';const bestKey=`${typingLanguage}Best_${activeGame}`;localStorage.setItem(bestKey,Math.max(gameScore,Number(localStorage.getItem(bestKey)||0)))}
document.addEventListener('keydown',e=>{if(gamesView.hidden||!gameRunning||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Shift')return;const key=physicalKey(e);const match=rowsForLanguage().flat().find(([mapped])=>mapped===key);if(match){e.preventDefault();acceptGameInput(e.shiftKey?match[2]:match[1],key,e.shiftKey)}});
function updateGameLanguage(){lastWord='';document.querySelector('#challengeWord').lang=languageTag();document.querySelector('#typedAnswer').lang=languageTag();document.querySelector('#fallingWord').lang=languageTag()}
window.addEventListener('typinglanguagechange',()=>{updateGameLanguage();if(!gameStage.hidden)resetGame()});updateGameLanguage();
