const karenLessons=[
  {title:'Basic letters',focus:'ဆ တ န မ အ ပ က င သ စ',text:'ဆ တ န မ အ ပ က င သ စ ဆ တ န မ အ ပ က င သ စ'},
  {title:'Vowels and marks',focus:'ါ ိ ု ူ ေ ဲ ၢ ၣ် ၤ',text:'ါ ိ ု ူ ေ ဲ ၢ ၣ် ၤ ါ ိ ု ူ ေ ဲ ၢ ၣ် ၤ'},
  {title:'Family words',focus:'ဟံၣ်ဖိဃီဖိ',text:'ဟံၣ်ဖိဃီဖိ မိၢ် ပၢ် မိၢ်ပၢ် ဖိခွါ ဖိမုၣ်'},
  {title:'Days of the week',focus:'မုၢ်ဒဲး',text:'မုၢ်ဒဲး မုၢ်ဆၣ် မုၢ်ယူာ် မုၢ်ပျဲၤ မုၢ်လ့ဧိၤ'},
  {title:'Food words',focus:'တၢ်အီၣ်',text:'တၢ်အီၣ် မ့ၤ ညၣ် ဆီညၣ် ထိးညၣ် ကျီၢ်ညၣ်'},
  {title:'Time expressions',focus:'ကိးနံၤဒဲး',text:'ကိးနံၤဒဲး ကိးဂီၤဒဲး ကိးဟါဒဲး ကိးနၤဒဲး ကိးနွံဒဲး'}
];
const englishLessons=[
  {title:'Home row',focus:'a s d f j k l',text:'a s d f j k l a s d f j k l'},
  {title:'Top row',focus:'q w e r t y u i o p',text:'q w e r t y u i o p q w e r t y'},
  {title:'Bottom row',focus:'z x c v b n m',text:'z x c v b n m z x c v b n m'},
  {title:'Common words',focus:'the and you',text:'the and you can type with good form'},
  {title:'School words',focus:'class book pencil',text:'class teacher student book pencil folder'},
  {title:'Capital letters',focus:'Shift + letter',text:'Karen English School Monday Friday'}
];
let lessons=typingLanguage==='en'?englishLessons:karenLessons;
const typeView=document.querySelector('#typeView'),practiceView=document.querySelector('#practiceView'),navType=document.querySelector('#navType'),navPractice=document.querySelector('#navPractice');
const lessonSelect=document.querySelector('#lessonSelect'),targetText=document.querySelector('#targetText'),practiceKeyboard=document.querySelector('#practiceKeyboard');
function lessonStorageKey(){return typingLanguage==='en'?'englishLesson':'karenLesson'}
let lessonIndex=Number(localStorage.getItem(lessonStorageKey())||0);if(lessonIndex>=lessons.length)lessonIndex=0;let position=0,attempts=0,errors=0,startTime=0,practiceShifted=false,chunks=[];
function rebuildLessonOptions(){lessonSelect.innerHTML='';lessons.forEach((lesson,i)=>{const option=document.createElement('option');option.value=i;option.textContent=`${i+1}. ${lesson.title}`;lessonSelect.appendChild(option)})}
rebuildLessonOptions();
function showView(view){const practice=view==='practice';typeView.hidden=practice;practiceView.hidden=!practice;const games=document.querySelector('#gamesView');if(games)games.hidden=true;if(typeof closeRace==='function')closeRace();navType.classList.toggle('active',!practice);navPractice.classList.toggle('active',practice);const gamesNav=document.querySelector('#navGames');if(gamesNav)gamesNav.classList.remove('active');if(practice){renderLesson();setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),0)}else editor.focus()}
navType.onclick=()=>showView('type');navPractice.onclick=()=>showView('practice');
function allMappings(language=typingLanguage){return mappingsForLanguage(language)}
function expectedMapping(){const target=lessons[lessonIndex].text;return allMappings().find(m=>target.startsWith(m.value,position))||({key:'Space',value:' ',shift:false})}
function renderLesson(){const lesson=lessons[lessonIndex];targetText.lang=typingLanguage==='en'?'en':'ksw';lessonSelect.value=lessonIndex;document.querySelector('#lessonNumber').textContent=`Lesson ${lessonIndex+1}`;document.querySelector('#lessonFocus').textContent=lesson.title;renderTarget();renderPracticeKeyboard();updateStats()}
function drawTypedHighlight(){targetText.querySelectorAll('.typed-progress').forEach(el=>el.remove());if(!position||!targetText.firstChild)return;const range=document.createRange();range.setStart(targetText.firstChild,0);range.setEnd(targetText.firstChild,Math.min(position,targetText.firstChild.length));const parent=targetText.getBoundingClientRect();[...range.getClientRects()].forEach(rect=>{if(!rect.width)return;const mark=document.createElement('span');mark.className='typed-progress';mark.setAttribute('aria-hidden','true');Object.assign(mark.style,{position:'absolute',pointerEvents:'none',left:`${rect.left-parent.left}px`,top:`${rect.top-parent.top}px`,width:`${rect.width}px`,height:`${rect.height}px`,background:'rgba(31,155,114,.18)',borderBottom:'3px solid #1f9b72',borderRadius:'4px'});targetText.appendChild(mark)})}
function renderTarget(){const text=lessons[lessonIndex].text;const expected=expectedMapping();targetText.textContent=text;requestAnimationFrame(drawTypedHighlight);if(document.fonts)document.fonts.ready.then(drawTypedHighlight);const label=document.querySelector('#nextKey');label.textContent=position>=text.length?'✓':expected.shift?`⇧ ${expected.key}`:expected.key==='Space'?'␣':expected.key;document.querySelector('#typePrompt').textContent=position>=text.length?'Lesson complete!':'Start typing with your English keyboard.';document.querySelector('#typePrompt').className=position>=text.length?'type-prompt complete':'type-prompt';document.querySelector('#nextLesson').hidden=position<text.length}
function renderPracticeKeyboard(){practiceKeyboard.innerHTML='';rowsForLanguage().forEach(row=>{const el=document.createElement('div');el.className='key-row';row.forEach(([key,normal,shift])=>{const b=document.createElement('button');b.type='button';b.className='key';b.dataset.code=key;b.innerHTML=`<small>${key}</small>${practiceShifted?shift:normal}`;b.onclick=()=>handlePractice(practiceShifted?shift:normal);el.appendChild(b)});practiceKeyboard.appendChild(el)});const bottom=document.createElement('div');bottom.className='key-row';const space=document.createElement('button');space.type='button';space.className='key wide space';space.dataset.code='Space';space.textContent='Space';space.onclick=()=>handlePractice(' ');bottom.appendChild(space);practiceKeyboard.appendChild(bottom);highlightExpected()}
function highlightExpected(){practiceKeyboard.querySelectorAll('.key').forEach(k=>k.classList.remove('expected'));if(position>=lessons[lessonIndex].text.length)return;const expected=expectedMapping();setPracticeShift(expected.shift);const key=practiceKeyboard.querySelector(`[data-code="${CSS.escape(expected.key)}"]`);if(key)key.classList.add('expected')}
function setPracticeShift(on){if(practiceShifted===on)return;practiceShifted=on;document.querySelector('#practiceNormal').classList.toggle('active',!on);document.querySelector('#practiceShift').classList.toggle('active',on);renderPracticeKeyboard()}
document.querySelector('#practiceNormal').onclick=()=>setPracticeShift(false);document.querySelector('#practiceShift').onclick=()=>setPracticeShift(true);
function handlePractice(value){const text=lessons[lessonIndex].text;if(position>=text.length)return;if(!startTime)startTime=Date.now();attempts++;if(text.startsWith(value,position)){chunks.push(value);position+=value.length;renderTarget();updateStats();highlightExpected();if(position>=text.length)localStorage.setItem(lessonStorageKey(),Math.min(lessonIndex+1,lessons.length-1))}else{errors++;const prompt=document.querySelector('#typePrompt');prompt.textContent='Try that key again.';prompt.className='type-prompt error';const expected=expectedMapping();const key=practiceKeyboard.querySelector(`[data-code="${CSS.escape(expected.key)}"]`);if(key){key.classList.add('wrong');setTimeout(()=>key.classList.remove('wrong'),220)}updateStats()}}
function updateStats(){const text=lessons[lessonIndex].text;const progress=Math.round(position/text.length*100);const accuracy=attempts?Math.max(0,Math.round((attempts-errors)/attempts*100)):100;const mins=startTime?Math.max((Date.now()-startTime)/60000,1/60):0;const typed=[...chunks.join('')].length;const wpm=mins?Math.round(typed/5/mins):0;document.querySelector('#progressStat').textContent=`${progress}%`;document.querySelector('#accuracyStat').textContent=`${accuracy}%`;document.querySelector('#wpmStat').textContent=wpm;document.querySelector('#progressBar').style.width=`${progress}%`}
function resetLesson(){position=0;attempts=0;errors=0;startTime=0;chunks=[];renderLesson()}
lessonSelect.onchange=()=>{lessonIndex=Number(lessonSelect.value);localStorage.setItem(lessonStorageKey(),lessonIndex);resetLesson()};document.querySelector('#restartLesson').onclick=resetLesson;document.querySelector('#nextLesson').onclick=()=>{lessonIndex=(lessonIndex+1)%lessons.length;localStorage.setItem(lessonStorageKey(),lessonIndex);resetLesson()};
document.addEventListener('keydown',e=>{if(practiceView.hidden||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Shift'){setPracticeShift(true);return}if(e.key==='Backspace'){e.preventDefault();if(chunks.length){const removed=chunks.pop();position-=removed.length;renderTarget();updateStats();highlightExpected()}return}if(e.key===' '){e.preventDefault();handlePractice(' ');return}const key=physicalKey(e);const match=rowsForLanguage().flat().find(([mapped])=>mapped===key);if(match){e.preventDefault();handlePractice(e.shiftKey?match[2]:match[1])}});document.addEventListener('keyup',e=>{if(!practiceView.hidden&&e.key==='Shift')highlightExpected()});
window.addEventListener('typinglanguagechange',()=>{lessons=typingLanguage==='en'?englishLessons:karenLessons;lessonIndex=Number(localStorage.getItem(lessonStorageKey())||0);if(lessonIndex>=lessons.length)lessonIndex=0;targetText.lang=typingLanguage==='en'?'en':'ksw';rebuildLessonOptions();resetLesson()});
window.addEventListener('resize',drawTypedHighlight);renderLesson();
