const navQuiz=document.querySelector('#navQuiz'),quizView=document.querySelector('#quizView'),quizBuilder=document.querySelector('#quizBuilder'),quizPlayer=document.querySelector('#quizPlayer'),quizResults=document.querySelector('#quizResults');
const quizPairs=document.querySelector('#quizPairs'),quizRelation=document.querySelector('#quizRelation'),quizDirection=document.querySelector('#quizDirection'),quizAnswerMode=document.querySelector('#quizAnswerMode'),quizTemplate=document.querySelector('#quizTemplate');
let generatedQuiz=[],quizIndex=0,quizPoints=0,quizBuffer='',quizSelected='',quizLocked=false,quizAnswers=[];

function openQuiz(){typeView.hidden=true;practiceView.hidden=true;gamesView.hidden=true;quizView.hidden=false;navType.classList.remove('active');navPractice.classList.remove('active');navGames.classList.remove('active');navQuiz.classList.add('active');if(typeof stopGame==='function')stopGame();if(typeof closeRace==='function')closeRace();quizBuilder.hidden=false;quizPlayer.hidden=true;quizResults.hidden=true;window.scrollTo({top:0,behavior:'smooth'})}
navQuiz.onclick=openQuiz;
quizRelation.onchange=()=>{document.querySelector('#quizTemplateField').hidden=quizRelation.value!=='custom'};

function parseQuizPairs(){return quizPairs.value.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map((line,index)=>{const divider=line.indexOf('=');if(divider<1||divider===line.length-1)throw new Error(`Line ${index+1} needs an equals sign between the two items.`);return{term:line.slice(0,divider).trim(),answer:line.slice(divider+1).trim()}})}
function questionFor(pair,index){const relation=quizRelation.value;const reverse=quizDirection.value==='reverse'||(quizDirection.value==='mixed'&&index%2===1);let question,answer,promptTerm;
  if(relation==='custom'){promptTerm=reverse?pair.answer:pair.term;question=quizTemplate.value.trim().replaceAll('{term}',promptTerm).replaceAll('{answer}',reverse?pair.term:pair.answer).replaceAll('{relationship}','answer');answer=reverse?pair.term:pair.answer}
  else{question=reverse?`What does “${pair.answer}” mean in English?`:`What is “${pair.term}” in ${languageName()}?`;answer=reverse?pair.term:pair.answer}
  const mode=quizAnswerMode.value==='mixed'?(index%2?'choice':'typing'):quizAnswerMode.value;return{...pair,relation,reverse,question,answer,mode}}
function generateQuestions(){const error=document.querySelector('#quizError');error.textContent='';try{const pairs=parseQuizPairs();if(!pairs.length)throw new Error('Add at least one word and answer pair.');if(quizRelation.value==='custom'&&!quizTemplate.value.includes('{term}'))throw new Error('The custom template must include {term}.');generatedQuiz=pairs.map(questionFor);renderQuizPreview()}catch(err){generatedQuiz=[];document.querySelector('#quizPreview').hidden=true;error.textContent=err.message}}
function renderQuizPreview(){document.querySelector('#quizPreview').hidden=false;document.querySelector('#quizPreviewCount').textContent=`${generatedQuiz.length} ${generatedQuiz.length===1?'question':'questions'}`;document.querySelector('#quizPreviewList').innerHTML=generatedQuiz.map(item=>`<li>${escapeQuizHtml(item.question)} <small>Answer: ${escapeQuizHtml(item.answer)}</small></li>`).join('')}
function escapeQuizHtml(value){const box=document.createElement('div');box.textContent=value;return box.innerHTML}
document.querySelector('#generateQuiz').onclick=generateQuestions;

function startQuiz(){if(!generatedQuiz.length){generateQuestions();if(!generatedQuiz.length)return}quizIndex=0;quizPoints=0;quizAnswers=[];quizBuilder.hidden=true;quizResults.hidden=true;quizPlayer.hidden=false;showQuizQuestion();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#startQuiz').onclick=startQuiz;
function currentQuiz(){return generatedQuiz[quizIndex]}
function showQuizQuestion(){const item=currentQuiz();quizBuffer='';quizSelected='';quizLocked=false;document.querySelector('#quizProgress').textContent=`Question ${quizIndex+1} of ${generatedQuiz.length}`;document.querySelector('#quizScore').textContent=`Score: ${quizPoints}`;document.querySelector('#quizProgressBar').style.width=`${quizIndex/generatedQuiz.length*100}%`;document.querySelector('#quizQuestion').textContent=item.question;document.querySelector('#quizType').textContent=item.mode==='choice'?'CHOOSE THE BEST ANSWER':'TYPE YOUR ANSWER';const typed=document.querySelector('#quizTypedAnswer');typed.textContent='';typed.className='quiz-typed-answer';typed.lang=quizAnswerLanguage(item);typed.hidden=item.mode==='choice';const choices=document.querySelector('#quizChoices');choices.hidden=item.mode!=='choice';document.querySelector('#quizFeedback').textContent='';document.querySelector('#quizFeedback').className='quiz-feedback';document.querySelector('#checkQuizAnswer').hidden=false;document.querySelector('#nextQuizQuestion').hidden=true;if(item.mode==='choice')renderQuizChoices();renderQuizKeyboard();if(item.mode==='typing')typed.focus()}
function quizAnswerLanguage(item){return hasMyanmar(item.answer)?languageTag():'en'}
function hasMyanmar(value){return /[\u1000-\u109f\ua9e0-\ua9ff\uaa60-\uaa7f]/iu.test(value)}
function shuffled(values){const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function renderQuizChoices(){const item=currentQuiz(),pool=generatedQuiz.map(question=>question.answer).filter((answer,index,array)=>array.indexOf(answer)===index),choices=shuffled([item.answer,...shuffled(pool.filter(answer=>answer!==item.answer)).slice(0,3)]);const box=document.querySelector('#quizChoices');box.innerHTML='';choices.forEach(value=>{const button=document.createElement('button');button.type='button';button.className='quiz-choice';button.textContent=value;button.onclick=()=>{if(quizLocked)return;quizSelected=value;box.querySelectorAll('.quiz-choice').forEach(choice=>choice.classList.toggle('selected',choice===button))};box.appendChild(button)})}
function normalizeQuizAnswer(value){return value.normalize('NFC').trim().replace(/\s+/g,' ').toLocaleLowerCase()}
function checkQuiz(){if(quizLocked)return;const item=currentQuiz(),response=item.mode==='choice'?quizSelected:quizBuffer;if(!response){document.querySelector('#quizFeedback').textContent=item.mode==='choice'?'Choose an answer first.':'Type an answer first.';return}quizLocked=true;const correct=normalizeQuizAnswer(response)===normalizeQuizAnswer(item.answer);if(correct)quizPoints++;quizAnswers.push({question:item.question,response,answer:item.answer,correct});const feedback=document.querySelector('#quizFeedback');feedback.textContent=correct?'Correct!':`Correct answer: ${item.answer}`;feedback.className=`quiz-feedback ${correct?'correct':'wrong'}`;if(item.mode==='typing'){document.querySelector('#quizTypedAnswer').classList.add(correct?'correct':'wrong')}else{document.querySelectorAll('.quiz-choice').forEach(choice=>{if(normalizeQuizAnswer(choice.textContent)===normalizeQuizAnswer(item.answer))choice.classList.add('correct');else if(choice.classList.contains('selected'))choice.classList.add('wrong')})}document.querySelector('#quizScore').textContent=`Score: ${quizPoints}`;document.querySelector('#checkQuizAnswer').hidden=true;document.querySelector('#nextQuizQuestion').hidden=false;document.querySelector('#nextQuizQuestion').textContent=quizIndex===generatedQuiz.length-1?'See results →':'Next question →'}
document.querySelector('#checkQuizAnswer').onclick=checkQuiz;
document.querySelector('#nextQuizQuestion').onclick=()=>{if(quizIndex<generatedQuiz.length-1){quizIndex++;showQuizQuestion()}else finishQuiz()};
function finishQuiz(){quizPlayer.hidden=true;quizResults.hidden=false;document.querySelector('#quizResultScore').textContent=`${quizPoints} out of ${generatedQuiz.length}`;const percent=Math.round(quizPoints/generatedQuiz.length*100);document.querySelector('#quizResultMessage').textContent=percent===100?'Excellent—every answer is correct!':percent>=80?'Great work! Review the questions below.':'Keep practicing and try the missed questions again.';document.querySelector('#quizReview').innerHTML=quizAnswers.map((item,index)=>`<div class="quiz-review-item ${item.correct?'':'missed'}"><span>${item.correct?'✓':'×'}</span><div><strong>${escapeQuizHtml(item.question)}</strong><small>Your answer: ${escapeQuizHtml(item.response)}</small></div><em>${item.correct?'Correct':`Answer: ${escapeQuizHtml(item.answer)}`}</em></div>`).join('');document.querySelector('#quizProgressBar').style.width='100%';window.scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#retryQuiz').onclick=startQuiz;document.querySelector('#newQuiz').onclick=()=>{quizResults.hidden=true;quizBuilder.hidden=false;window.scrollTo({top:0,behavior:'smooth'})};document.querySelector('#editQuiz').onclick=()=>{quizPlayer.hidden=true;quizBuilder.hidden=false};

function quizRows(){return hasMyanmar(currentQuiz()?.answer||'')?rowsForLanguage():englishRows}
function quizExpected(){const item=currentQuiz();if(!item||!hasMyanmar(item.answer))return null;return mappingsForLanguage().find(mapping=>item.answer.startsWith(mapping.value,quizBuffer.length))||null}
function quizBackspace(){if(quizLocked||!quizBuffer)return;quizBuffer=quizBuffer.slice(0,previousTextBoundary(quizBuffer,quizBuffer.length));document.querySelector('#quizTypedAnswer').textContent=quizBuffer;renderQuizKeyboard()}
function addQuizCharacter(value){if(quizLocked||currentQuiz().mode!=='typing')return;quizBuffer+=value;document.querySelector('#quizTypedAnswer').textContent=quizBuffer;renderQuizKeyboard()}
function quizControl(label,action,active=false){const button=document.createElement('button');button.type='button';button.className='key wide';button.textContent=label;button.onclick=action;if(active)button.classList.add('expected');return button}
function renderQuizKeyboard(){const box=document.querySelector('#quizKeyboard');box.innerHTML='';const item=currentQuiz();if(!item||item.mode!=='typing'){box.hidden=true;return}box.hidden=false;const expected=quizExpected(),useShift=expected?.shift||false,mobile=phoneKeyboard();quizRows().forEach((row,rowIndex)=>{const line=document.createElement('div');line.className='key-row';if(mobile&&rowIndex===3)line.appendChild(quizControl('Shift',()=>{},useShift));row.forEach(([key,normal,shift])=>{const button=document.createElement('button');button.type='button';button.className='key';button.dataset.code=key;button.innerHTML=`<small>${key}</small>${useShift?shift:normal}`;if(expected?.key===key)button.classList.add('expected');button.onclick=()=>addQuizCharacter(useShift?shift:normal);line.appendChild(button)});if(rowIndex===0&&!mobile)line.appendChild(quizControl('Backspace',quizBackspace));if(rowIndex===3&&mobile)line.appendChild(quizControl('⌫',quizBackspace));box.appendChild(line)});const bottom=document.createElement('div');bottom.className='key-row phone-bottom-row';if(!mobile)bottom.appendChild(quizControl('Shift',()=>{},useShift));const space=quizControl('Space',()=>addQuizCharacter(' '),expected?.key==='Space');space.classList.add('space');bottom.appendChild(space);bottom.appendChild(quizControl('Enter',()=>quizLocked?document.querySelector('#nextQuizQuestion').click():checkQuiz()));box.appendChild(bottom)}
document.addEventListener('keydown',event=>{if(quizView.hidden||quizPlayer.hidden||currentQuiz()?.mode!=='typing'||event.ctrlKey||event.metaKey||event.altKey)return;if(event.key==='Enter'){event.preventDefault();quizLocked?document.querySelector('#nextQuizQuestion').click():checkQuiz();return}if(quizLocked)return;if(event.key==='Backspace'){event.preventDefault();quizBackspace();return}if(hasMyanmar(currentQuiz().answer)){if(event.key==='Shift')return;const key=physicalKey(event),match=rowsForLanguage().flat().find(([mapped])=>mapped===key);if(match){event.preventDefault();addQuizCharacter(event.shiftKey?match[2]:match[1])}}else if(event.key.length===1){event.preventDefault();addQuizCharacter(event.key)}});
window.addEventListener('typinglanguagechange',()=>{if(!quizView.hidden&&generatedQuiz.length)generateQuestions();if(!quizPlayer.hidden)showQuizQuestion()});
generateQuestions();
