const seatEl=id=>document.querySelector(id);
const seatingClassName=seatEl('#seatingClassName'),seatingClassSelect=seatEl('#seatingClassSelect'),seatingRoster=seatEl('#seatingRoster'),seatingRows=seatEl('#seatingRows'),seatingColumns=seatEl('#seatingColumns'),seatingGrid=seatEl('#seatingGrid'),seatingBoard=seatEl('#seatingBoard'),seatingChartName=seatEl('#seatingChartName'),seatingLocalMode=seatEl('#seatingLocalMode'),seatingGoogleMode=seatEl('#seatingGoogleMode'),seatingGoogleSignIn=seatEl('#seatingGoogleSignIn'),seatingStorageStatus=seatEl('#seatingStorageStatus');
const defaultRoster=['Alex','Maria','Saw Htoo','Naw Paw','Jordan','Taylor'];
const blankClass=(name='My Class')=>({id:`class-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,className:name,roster:[],rows:5,columns:6,seats:[],locked:[],flipped:false,rules:{keepApart:'',nearFront:'',alternate:false,groupA:'',groupB:''},updatedAt:Date.now()});
let seatingClasses=[],activeClassId='',seatingState=blankClass(),seatingStorageMode=localStorage.getItem('glnSeatingStorageMode')||'local',seatingSaveTimer=null,seatingDraggedIndex=null;
for(let value=2;value<=10;value++){seatingRows.add(new Option(String(value),String(value)));seatingColumns.add(new Option(String(value),String(value)));seatEl('#seatingGroupCount').add(new Option(String(value),String(value)))}
function lines(value){return String(value||'').split(/\r?\n/).map(v=>v.trim()).filter(Boolean)}
function rosterNames(){return lines(seatingRoster.value).slice(0,100)}
function readRules(){return{keepApart:seatEl('#seatingKeepApart').value,nearFront:seatEl('#seatingNearFront').value,alternate:seatEl('#seatingAlternateGender').checked,groupA:seatEl('#seatingGroupA').value,groupB:seatEl('#seatingGroupB').value}}
function capture(){seatingState={...seatingState,className:seatingClassName.value.trim()||'My Class',roster:rosterNames(),rows:Number(seatingRows.value)||5,columns:Number(seatingColumns.value)||6,rules:readRules(),updatedAt:Date.now()};return seatingState}
function normalize(data={}){const base=blankClass();return{...base,...data,id:String(data.id||base.id),className:String(data.className||'My Class').slice(0,50),roster:Array.isArray(data.roster)?data.roster.slice(0,100):[],rows:Math.max(2,Math.min(10,Number(data.rows)||5)),columns:Math.max(2,Math.min(10,Number(data.columns)||6)),seats:Array.isArray(data.seats)?data.seats.slice(0,100):[],locked:Array.isArray(data.locked)?data.locked.slice(0,100):[],rules:{...base.rules,...(data.rules||{})}}}
function refreshMenu(){seatingClassSelect.innerHTML='';seatingClasses.forEach(item=>seatingClassSelect.add(new Option(item.className,item.id)));seatingClassSelect.value=activeClassId}
function applyState(data){seatingState=normalize(data);activeClassId=seatingState.id;seatingClassName.value=seatingState.className;seatingRoster.value=seatingState.roster.join('\n');seatingRows.value=seatingState.rows;seatingColumns.value=seatingState.columns;seatEl('#seatingKeepApart').value=seatingState.rules.keepApart;seatEl('#seatingNearFront').value=seatingState.rules.nearFront;seatEl('#seatingAlternateGender').checked=seatingState.rules.alternate;seatEl('#seatingGroupA').value=seatingState.rules.groupA;seatEl('#seatingGroupB').value=seatingState.rules.groupB;refreshMenu();renderSeatingChart()}
function upsert(){capture();const index=seatingClasses.findIndex(item=>item.id===activeClassId);if(index<0)seatingClasses.push(seatingState);else seatingClasses[index]=structuredClone(seatingState);refreshMenu()}
function payload(){return{activeClassId,classes:seatingClasses,updatedAt:Date.now()}}
function saveLocal(){upsert();localStorage.setItem('glnSeatingClasses',JSON.stringify(payload()));seatingStorageStatus.textContent='Saved locally on this device';seatingStorageStatus.classList.add('synced')}
async function saveCloud(){if(seatingStorageMode!=='google'||!currentUser||currentUser.isAnonymous)return;try{upsert();await fb.set(fb.ref(db,`seatingCharts/${currentUser.uid}`),payload());seatingStorageStatus.textContent=`Synced with ${currentUser.email||'Google account'}`;seatingStorageStatus.classList.add('synced')}catch{seatingStorageStatus.textContent='Could not sync. Your local copy is still saved.';seatingStorageStatus.classList.remove('synced')}}
function queueSave(){saveLocal();clearTimeout(seatingSaveTimer);if(seatingStorageMode==='google')seatingSaveTimer=setTimeout(saveCloud,600)}
function shuffled(items){const list=[...items];for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function arrangement(names,count){const rules=readRules(),front=new Set(lines(rules.nearFront)),aSet=new Set(lines(rules.groupA)),bSet=new Set(lines(rules.groupB));let pool=shuffled(names),ordered=[...pool.filter(name=>front.has(name))];pool=pool.filter(name=>!front.has(name));if(rules.alternate){const a=shuffled(pool.filter(name=>aSet.has(name))),b=shuffled(pool.filter(name=>bSet.has(name))),other=pool.filter(name=>!aSet.has(name)&&!bSet.has(name));while(a.length||b.length){if(a.length)ordered.push(a.shift());if(b.length)ordered.push(b.shift())}ordered.push(...shuffled(other))}else ordered.push(...pool);while(ordered.length<count)ordered.push(null);const pairs=lines(rules.keepApart).map(row=>row.split(',').map(v=>v.trim())).filter(pair=>pair.length===2&&pair[0]&&pair[1]);for(let pass=0;pass<6;pass++)pairs.forEach(([a,b])=>{const ai=ordered.indexOf(a),bi=ordered.indexOf(b);if(ai<0||bi<0)return;const distance=i=>Math.abs(Math.floor(ai/seatingState.columns)-Math.floor(i/seatingState.columns))+Math.abs(ai%seatingState.columns-i%seatingState.columns);if(distance(bi)<=1){const far=ordered.findIndex((_,i)=>i!==ai&&i!==bi&&!seatingState.locked[i]&&distance(i)>1);if(far>=0)[ordered[bi],ordered[far]]=[ordered[far],ordered[bi]]}});return ordered.slice(0,count)}
function buildChart(){capture();const count=seatingState.rows*seatingState.columns;if(seatingState.roster.length>count)showToast(`Add more seats for ${seatingState.roster.length-count} students`);seatingState.locked=Array(count).fill(false);seatingState.seats=arrangement(seatingState.roster.slice(0,count),count);renderSeatingChart();queueSave()}
function renderSeatingChart(){const count=seatingState.rows*seatingState.columns;seatingState.seats=seatingState.seats.slice(0,count);while(seatingState.seats.length<count)seatingState.seats.push(null);seatingState.locked=seatingState.locked.slice(0,count);while(seatingState.locked.length<count)seatingState.locked.push(false);seatingChartName.textContent=seatingClassName.value.trim()||seatingState.className;seatingBoard.classList.toggle('flipped',seatingState.flipped);seatingGrid.style.gridTemplateColumns=`repeat(${seatingState.columns},minmax(88px,1fr))`;seatingGrid.innerHTML='';const rows=[...Array(seatingState.rows).keys()];if(seatingState.flipped)rows.reverse();rows.forEach(row=>{for(let column=0;column<seatingState.columns;column++){const index=row*seatingState.columns+column,name=seatingState.seats[index],seat=document.createElement('article');seat.className=`student-seat${name?'':' empty'}${seatingState.locked[index]?' locked':''}`;seat.draggable=Boolean(name&&!seatingState.locked[index]);seat.innerHTML=`<span class="seat-number">${index+1}</span><span>${name||'Empty'}</span>`;if(name){const lock=document.createElement('button');lock.type='button';lock.className='seat-lock';lock.textContent=seatingState.locked[index]?'🔒':'🔓';lock.onclick=e=>{e.stopPropagation();seatingState.locked[index]=!seatingState.locked[index];renderSeatingChart();queueSave()};seat.append(lock)}seat.ondragstart=()=>{seatingDraggedIndex=index;seat.classList.add('dragging')};seat.ondragend=()=>{seatingDraggedIndex=null;seat.classList.remove('dragging')};seat.ondragover=e=>{if(seatingDraggedIndex!==null&&!seatingState.locked[index]){e.preventDefault();seat.classList.add('drag-over')}};seat.ondragleave=()=>seat.classList.remove('drag-over');seat.ondrop=e=>{e.preventDefault();seat.classList.remove('drag-over');if(seatingDraggedIndex===null||seatingState.locked[index]||seatingState.locked[seatingDraggedIndex])return;[seatingState.seats[index],seatingState.seats[seatingDraggedIndex]]=[seatingState.seats[seatingDraggedIndex],seatingState.seats[index]];renderSeatingChart();queueSave()};seatingGrid.append(seat)}})}
function shuffleChart(){const open=seatingState.seats.map((_,i)=>i).filter(i=>!seatingState.locked[i]),names=open.map(i=>seatingState.seats[i]).filter(Boolean),arranged=arrangement(names,open.length);open.forEach((i,p)=>seatingState.seats[i]=arranged[p]||null);renderSeatingChart();queueSave()}
function createGroups(){const count=Number(seatEl('#seatingGroupCount').value)||2,names=shuffled(rosterNames()),groups=Array.from({length:count},()=>[]);names.forEach((name,i)=>groups[i%count].push(name));seatEl('#seatingGroupResults').innerHTML=groups.map((group,i)=>`<section><strong>Group ${i+1}</strong><p>${group.join('<br>')||'—'}</p></section>`).join('')}
function importRoster(file){const reader=new FileReader();reader.onload=()=>{let rows=String(reader.result||'').split(/\r?\n/).map(row=>row.split(',')[0].replace(/^\s*["']|["']\s*$/g,'').trim()).filter(Boolean);if(/^(student|name|student name)$/i.test(rows[0]||''))rows.shift();seatingRoster.value=rows.slice(0,100).join('\n');showToast(`${Math.min(rows.length,100)} students imported`);queueSave()};reader.readAsText(file)}
function downloadChart(){const scale=2,cellW=180,cellH=100,pad=50,width=Math.max(700,seatingState.columns*cellW+pad*2),height=190+seatingState.rows*cellH,canvas=document.createElement('canvas');canvas.width=width*scale;canvas.height=height*scale;const c=canvas.getContext('2d');c.scale(scale,scale);c.fillStyle='#f4f8fc';c.fillRect(0,0,width,height);c.fillStyle='#173868';c.font='bold 28px sans-serif';c.textAlign='center';c.fillText(seatingClassName.value||'My Class',width/2,42);c.fillRect(width*.25,65,width*.5,38);c.fillStyle='#fff';c.font='bold 14px sans-serif';c.fillText('FRONT OF ROOM',width/2,90);seatingState.seats.forEach((name,i)=>{const row=Math.floor(i/seatingState.columns),col=i%seatingState.columns,x=pad+col*cellW,y=125+row*cellH;c.fillStyle=name?'#fff':'#e8eef5';c.strokeStyle=seatingState.locked[i]?'#e6a700':'#b8c9dc';c.lineWidth=3;c.beginPath();c.roundRect(x+8,y+8,cellW-16,cellH-16,12);c.fill();c.stroke();c.fillStyle='#173868';c.font='bold 16px sans-serif';c.fillText(name||'Empty',x+cellW/2,y+58,cellW-30)});const link=document.createElement('a');link.download=`${(seatingClassName.value||'seating-chart').replace(/[^a-z0-9]+/gi,'-')}.png`;link.href=canvas.toDataURL('image/png');link.click()}
function setStorage(mode){seatingStorageMode=mode;localStorage.setItem('glnSeatingStorageMode',mode);seatingLocalMode.classList.toggle('active',mode==='local');seatingGoogleMode.classList.toggle('active',mode==='google');const signed=Boolean(currentUser&&!currentUser.isAnonymous);seatingGoogleSignIn.hidden=mode!=='google'||signed;if(mode==='local')saveLocal();else if(signed)loadCloud();else initializeAccount()}
async function initializeAccount(){try{await initRaceFirebase();if(currentUser&&!currentUser.isAnonymous){seatingGoogleSignIn.hidden=true;await loadCloud()}else{seatingGoogleSignIn.hidden=false;seatingStorageStatus.textContent='Sign in to sync all classes across devices'}}catch{seatingGoogleSignIn.hidden=false;seatingStorageStatus.textContent='Google sync is not configured yet.'}}
async function signInGoogle(){seatingGoogleSignIn.disabled=true;try{await initRaceFirebase();const provider=new fb.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const credential=await fb.signInWithPopup(auth,provider);currentUser=credential.user;seatingGoogleSignIn.hidden=true;await loadCloud()}catch{seatingStorageStatus.textContent='Google sign-in was not completed.'}finally{seatingGoogleSignIn.disabled=false}}
async function loadCloud(){if(!currentUser||currentUser.isAnonymous)return;try{const snapshot=await fb.get(fb.ref(db,`seatingCharts/${currentUser.uid}`));if(snapshot.exists()){const data=snapshot.val();if(Array.isArray(data.classes)&&data.classes.length){seatingClasses=data.classes.map(normalize);activeClassId=data.activeClassId||seatingClasses[0].id;applyState(seatingClasses.find(c=>c.id===activeClassId)||seatingClasses[0])}}else await saveCloud();seatingStorageStatus.textContent=`Synced with ${currentUser.email||'Google account'}`;seatingStorageStatus.classList.add('synced')}catch{seatingStorageStatus.textContent='Could not load the cloud copy.'}}
const saved=JSON.parse(localStorage.getItem('glnSeatingClasses')||'null');if(saved?.classes?.length){seatingClasses=saved.classes.map(normalize);activeClassId=saved.activeClassId||seatingClasses[0].id}else{const legacy=JSON.parse(localStorage.getItem('glnSeatingChart')||'null'),initial=normalize(legacy||{className:'My Class',roster:defaultRoster});seatingClasses=[initial];activeClassId=initial.id}applyState(seatingClasses.find(c=>c.id===activeClassId)||seatingClasses[0]);
seatingClassSelect.onchange=()=>{saveLocal();applyState(seatingClasses.find(c=>c.id===seatingClassSelect.value)||seatingClasses[0])};seatEl('#newSeatingClass').onclick=()=>{saveLocal();const item=blankClass(`Class ${seatingClasses.length+1}`);seatingClasses.push(item);applyState(item);queueSave()};seatEl('#deleteSeatingClass').onclick=()=>{if(seatingClasses.length===1){showToast('Keep at least one class');return}if(!confirm(`Delete ${seatingState.className}?`))return;seatingClasses=seatingClasses.filter(c=>c.id!==activeClassId);applyState(seatingClasses[0]);queueSave()};
seatEl('#buildSeating').onclick=buildChart;seatEl('#shuffleSeating').onclick=shuffleChart;seatEl('#flipSeating').onclick=()=>{seatingState.flipped=!seatingState.flipped;renderSeatingChart();queueSave()};seatEl('#makeSeatingGroups').onclick=createGroups;seatEl('#importSeatingRoster').onclick=()=>seatEl('#seatingFileInput').click();seatEl('#seatingFileInput').onchange=e=>{if(e.target.files[0])importRoster(e.target.files[0]);e.target.value=''};seatEl('#downloadSeating').onclick=downloadChart;seatingLocalMode.onclick=()=>setStorage('local');seatingGoogleMode.onclick=()=>setStorage('google');seatingGoogleSignIn.onclick=signInGoogle;seatEl('#seatingFullscreen').onclick=()=>{if(!document.fullscreenElement)seatEl('#seatingPanel').requestFullscreen?.();else document.exitFullscreen?.()};seatEl('#printSeating').onclick=()=>{document.body.classList.add('print-seating');window.print()};window.addEventListener('afterprint',()=>document.body.classList.remove('print-seating'));[seatingClassName,seatingRoster,seatEl('#seatingKeepApart'),seatEl('#seatingNearFront'),seatEl('#seatingGroupA'),seatEl('#seatingGroupB')].forEach(input=>input.addEventListener('change',queueSave));seatEl('#seatingAlternateGender').onchange=queueSave;setStorage(seatingStorageMode);window.renderSeatingChart=renderSeatingChart;
