const seatEl=id=>document.querySelector(id);
const seatingClassName=seatEl('#seatingClassName'),seatingClassSelect=seatEl('#seatingClassSelect'),seatingRoster=seatEl('#seatingRoster'),seatingRows=seatEl('#seatingRows'),seatingColumns=seatEl('#seatingColumns'),seatingGrid=seatEl('#seatingGrid'),seatingBoard=seatEl('#seatingBoard'),seatingChartName=seatEl('#seatingChartName'),seatingLocalMode=seatEl('#seatingLocalMode'),seatingGoogleMode=seatEl('#seatingGoogleMode'),seatingGoogleSignIn=seatEl('#seatingGoogleSignIn'),seatingStorageStatus=seatEl('#seatingStorageStatus');
const defaultRoster=['Alex','Maria','Saw Htoo','Naw Paw','Jordan','Taylor'];
const blankClass=(name='My Class')=>({id:`class-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,className:name,roster:[],rows:5,columns:6,seats:[],locked:[],flipped:false,layoutMode:'grid',deskLayout:[],rules:{keepApart:'',nearFront:'',alternate:false,groupA:'',groupB:''},updatedAt:Date.now()});
let seatingClasses=[],activeClassId='',seatingState=blankClass(),seatingStorageMode=localStorage.getItem('glnSeatingStorageMode')||'local',seatingSaveTimer=null,seatingDraggedIndex=null,selectedDesks=new Set(),deskUndo=[],deskRedo=[],layoutEditing=false;
for(let value=2;value<=10;value++){seatingRows.add(new Option(String(value),String(value)));seatingColumns.add(new Option(String(value),String(value)));seatEl('#seatingGroupCount').add(new Option(String(value),String(value)))}
function lines(value){return String(value||'').split(/\r?\n/).map(v=>v.trim()).filter(Boolean)}
function rosterNames(){return lines(seatingRoster.value).slice(0,100)}
function readRules(){return{keepApart:seatEl('#seatingKeepApart').value,nearFront:seatEl('#seatingNearFront').value,alternate:seatEl('#seatingAlternateGender').checked,groupA:seatEl('#seatingGroupA').value,groupB:seatEl('#seatingGroupB').value}}
function capture(){seatingState={...seatingState,className:seatingClassName.value.trim()||'My Class',roster:rosterNames(),rows:Number(seatingRows.value)||5,columns:Number(seatingColumns.value)||6,rules:readRules(),updatedAt:Date.now()};return seatingState}
function normalize(data={}){const base=blankClass();return{...base,...data,id:String(data.id||base.id),className:String(data.className||'My Class').slice(0,50),roster:Array.isArray(data.roster)?data.roster.slice(0,100):[],rows:Math.max(2,Math.min(10,Number(data.rows)||5)),columns:Math.max(2,Math.min(10,Number(data.columns)||6)),seats:Array.isArray(data.seats)?data.seats.slice(0,100):[],locked:Array.isArray(data.locked)?data.locked.slice(0,100):[],layoutMode:data.layoutMode==='custom'?'custom':'grid',deskLayout:Array.isArray(data.deskLayout)?data.deskLayout:[],rules:{...base.rules,...(data.rules||{})}}}
function refreshMenu(){seatingClassSelect.innerHTML='';seatingClasses.forEach(item=>seatingClassSelect.add(new Option(item.className,item.id)));seatingClassSelect.value=activeClassId}
function applyState(data){seatingState=normalize(data);activeClassId=seatingState.id;selectedDesks.clear();deskUndo=[];deskRedo=[];seatingClassName.value=seatingState.className;seatingRoster.value=seatingState.roster.join('\n');seatingRows.value=seatingState.rows;seatingColumns.value=seatingState.columns;seatEl('#seatingKeepApart').value=seatingState.rules.keepApart;seatEl('#seatingNearFront').value=seatingState.rules.nearFront;seatEl('#seatingAlternateGender').checked=seatingState.rules.alternate;seatEl('#seatingGroupA').value=seatingState.rules.groupA;seatEl('#seatingGroupB').value=seatingState.rules.groupB;refreshMenu();renderSeatingChart()}
function upsert(){capture();const index=seatingClasses.findIndex(item=>item.id===activeClassId);if(index<0)seatingClasses.push(seatingState);else seatingClasses[index]=structuredClone(seatingState);refreshMenu()}
function payload(){return{activeClassId,classes:seatingClasses,updatedAt:Date.now()}}
function saveLocal(){upsert();localStorage.setItem('glnSeatingClasses',JSON.stringify(payload()));seatingStorageStatus.textContent='Saved locally on this device';seatingStorageStatus.classList.add('synced')}
async function saveCloud(){if(seatingStorageMode!=='google'||!currentUser||currentUser.isAnonymous)return;try{upsert();await fb.set(fb.ref(db,`seatingCharts/${currentUser.uid}`),payload());seatingStorageStatus.textContent=`Synced with ${currentUser.email||'Google account'}`;seatingStorageStatus.classList.add('synced')}catch{seatingStorageStatus.textContent='Could not sync. Your local copy is still saved.';seatingStorageStatus.classList.remove('synced')}}
function queueSave(){saveLocal();clearTimeout(seatingSaveTimer);if(seatingStorageMode==='google')seatingSaveTimer=setTimeout(saveCloud,600)}
function shuffled(items){const list=[...items];for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function arrangement(names,count){const rules=readRules(),front=new Set(lines(rules.nearFront)),aSet=new Set(lines(rules.groupA)),bSet=new Set(lines(rules.groupB));let pool=shuffled(names),ordered=[...pool.filter(name=>front.has(name))];pool=pool.filter(name=>!front.has(name));if(rules.alternate){const a=shuffled(pool.filter(name=>aSet.has(name))),b=shuffled(pool.filter(name=>bSet.has(name))),other=pool.filter(name=>!aSet.has(name)&&!bSet.has(name));while(a.length||b.length){if(a.length)ordered.push(a.shift());if(b.length)ordered.push(b.shift())}ordered.push(...shuffled(other))}else ordered.push(...pool);while(ordered.length<count)ordered.push(null);const pairs=lines(rules.keepApart).map(row=>row.split(',').map(v=>v.trim())).filter(pair=>pair.length===2&&pair[0]&&pair[1]);for(let pass=0;pass<6;pass++)pairs.forEach(([a,b])=>{const ai=ordered.indexOf(a),bi=ordered.indexOf(b);if(ai<0||bi<0)return;const distance=i=>Math.abs(Math.floor(ai/seatingState.columns)-Math.floor(i/seatingState.columns))+Math.abs(ai%seatingState.columns-i%seatingState.columns);if(distance(bi)<=1){const far=ordered.findIndex((_,i)=>i!==ai&&i!==bi&&!seatingState.locked[i]&&distance(i)>1);if(far>=0)[ordered[bi],ordered[far]]=[ordered[far],ordered[bi]]}});return ordered.slice(0,count)}
function buildChart(){capture();const count=seatingState.rows*seatingState.columns;if(seatingState.roster.length>count)showToast(`Add more seats for ${seatingState.roster.length-count} students`);seatingState.layoutMode='grid';seatingState.deskLayout=[];seatingState.locked=Array(count).fill(false);seatingState.seats=arrangement(seatingState.roster.slice(0,count),count);renderSeatingChart();queueSave()}
function renderSeatingChart(){seatingChartName.textContent=seatingClassName.value.trim()||seatingState.className;seatingBoard.classList.toggle('flipped',seatingState.flipped);seatingBoard.classList.toggle('custom-layout',seatingState.layoutMode==='custom');seatingBoard.classList.toggle('editing',layoutEditing);seatEl('#editDeskLayout').textContent=layoutEditing?'Finish editing':'Edit layout';if(seatingState.layoutMode==='custom'){renderCustomLayoutV2();return}const count=seatingState.rows*seatingState.columns;seatingState.seats=seatingState.seats.slice(0,count);while(seatingState.seats.length<count)seatingState.seats.push(null);seatingState.locked=seatingState.locked.slice(0,count);while(seatingState.locked.length<count)seatingState.locked.push(false);seatingGrid.style.gridTemplateColumns=`repeat(${seatingState.columns},minmax(88px,1fr))`;seatingGrid.innerHTML='';const rows=[...Array(seatingState.rows).keys()];if(seatingState.flipped)rows.reverse();rows.forEach(row=>{for(let column=0;column<seatingState.columns;column++){const index=row*seatingState.columns+column,name=seatingState.seats[index],seat=document.createElement('article');seat.className=`student-seat${name?'':' empty'}${seatingState.locked[index]?' locked':''}`;seat.draggable=Boolean(name&&!seatingState.locked[index]);seat.innerHTML=`<span class="seat-number">${index+1}</span><span>${name||'Empty'}</span>`;if(name){const lock=document.createElement('button');lock.type='button';lock.className='seat-lock';lock.textContent=seatingState.locked[index]?'🔒':'🔓';lock.onclick=e=>{e.stopPropagation();seatingState.locked[index]=!seatingState.locked[index];renderSeatingChart();queueSave()};seat.append(lock)}seat.ondragstart=()=>{seatingDraggedIndex=index;seat.classList.add('dragging')};seat.ondragend=()=>{seatingDraggedIndex=null;seat.classList.remove('dragging')};seat.ondragover=e=>{if(seatingDraggedIndex!==null&&!seatingState.locked[index]){e.preventDefault();seat.classList.add('drag-over')}};seat.ondragleave=()=>seat.classList.remove('drag-over');seat.ondrop=e=>{e.preventDefault();seat.classList.remove('drag-over');if(seatingDraggedIndex===null||seatingState.locked[index]||seatingState.locked[seatingDraggedIndex])return;[seatingState.seats[index],seatingState.seats[seatingDraggedIndex]]=[seatingState.seats[seatingDraggedIndex],seatingState.seats[index]];renderSeatingChart();queueSave()};seatingGrid.append(seat)}})}
function gridToCustom(){const cols=seatingState.columns||6;seatingState.deskLayout=seatingState.seats.map((_,i)=>({id:`desk-${Date.now()}-${i}`,x:25+(i%cols)*115,y:20+Math.floor(i/cols)*90,w:98,h:68,rotation:0}));seatingState.layoutMode='custom'}
function deskSnapshot(){return JSON.stringify({deskLayout:seatingState.deskLayout,seats:seatingState.seats,locked:seatingState.locked,layoutMode:seatingState.layoutMode})}
function pushDeskHistory(){deskUndo.push(deskSnapshot());if(deskUndo.length>40)deskUndo.shift();deskRedo=[]}
function restoreDeskSnapshot(value){const data=JSON.parse(value);seatingState.deskLayout=data.deskLayout;seatingState.seats=data.seats;seatingState.locked=data.locked;seatingState.layoutMode=data.layoutMode;selectedDesks.clear();renderSeatingChart();queueSave()}
function renderCustomLayout(){seatingGrid.innerHTML='';seatingGrid.style.gridTemplateColumns='none';seatingState.deskLayout.forEach((desk,index)=>{const name=seatingState.seats[index],el=document.createElement('article');el.className=`student-seat custom-desk${name?'':' empty'}${selectedDesks.has(desk.id)?' selected':''}`;el.dataset.deskId=desk.id;el.style.cssText=`left:${desk.x}px;top:${desk.y}px;width:${desk.w}px;height:${desk.h}px;transform:rotate(${desk.rotation||0}deg)`;el.innerHTML=`<span class="seat-number">${index+1}</span><span>${name||'Empty'}</span><i class="desk-resize" aria-hidden="true"></i>`;el.onpointerdown=e=>{if(!layoutEditing||e.target.classList.contains('desk-resize'))return;e.preventDefault();if(e.shiftKey){if(selectedDesks.has(desk.id))selectedDesks.delete(desk.id);else selectedDesks.add(desk.id);renderCustomLayout();return}if(!selectedDesks.has(desk.id)){selectedDesks.clear();selectedDesks.add(desk.id)}pushDeskHistory();const startX=e.clientX,startY=e.clientY,origins=new Map(seatingState.deskLayout.filter(d=>selectedDesks.has(d.id)).map(d=>[d.id,{x:d.x,y:d.y}]));const move=event=>{const snap=seatEl('#snapDesks').checked?10:1;seatingState.deskLayout.forEach(d=>{const origin=origins.get(d.id);if(origin){d.x=Math.max(0,Math.round((origin.x+event.clientX-startX)/snap)*snap);d.y=Math.max(0,Math.round((origin.y+event.clientY-startY)/snap)*snap)}});renderCustomLayout()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);queueSave()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)};el.querySelector('.desk-resize').onpointerdown=e=>{if(!layoutEditing)return;e.preventDefault();e.stopPropagation();pushDeskHistory();selectedDesks.clear();selectedDesks.add(desk.id);const sx=e.clientX,sy=e.clientY,ow=desk.w,oh=desk.h;const move=event=>{const snap=seatEl('#snapDesks').checked?10:1;desk.w=Math.max(60,Math.round((ow+event.clientX-sx)/snap)*snap);desk.h=Math.max(45,Math.round((oh+event.clientY-sy)/snap)*snap);renderCustomLayout()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);queueSave()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)};seatingGrid.append(el)});const maxY=Math.max(480,...seatingState.deskLayout.map(d=>d.y+d.h+30));seatingGrid.style.minHeight=`${maxY}px`}
function gridPoint(event){const box=seatingGrid.getBoundingClientRect();return{x:event.clientX-box.left,y:event.clientY-box.top}}
function refreshDeskSelection(){seatingGrid.querySelectorAll('.custom-desk').forEach(el=>el.classList.toggle('selected',selectedDesks.has(el.dataset.deskId)))}
function renderCustomLayoutV2(){
  seatingGrid.innerHTML='';seatingGrid.style.gridTemplateColumns='none';
  seatingState.deskLayout.forEach((desk,index)=>{
    const name=seatingState.seats[index],el=document.createElement('article');
    el.className=`student-seat custom-desk${name?'':' empty'}${selectedDesks.has(desk.id)?' selected':''}`;el.dataset.deskId=desk.id;
    el.style.cssText=`left:${desk.x}px;top:${desk.y}px;width:${desk.w}px;height:${desk.h}px;transform:rotate(${desk.rotation||0}deg)`;
    el.innerHTML=`<span class="seat-number">${index+1}</span><span>${name||'Empty'}</span><i class="desk-resize" aria-label="Resize selected desks"></i>`;
    el.onpointerdown=event=>{
      if(!layoutEditing||event.target.classList.contains('desk-resize'))return;event.preventDefault();event.stopPropagation();
      if(event.shiftKey){selectedDesks.has(desk.id)?selectedDesks.delete(desk.id):selectedDesks.add(desk.id);refreshDeskSelection();return}
      if(!selectedDesks.has(desk.id)){selectedDesks.clear();selectedDesks.add(desk.id);refreshDeskSelection()}
      pushDeskHistory();const start=gridPoint(event),origins=new Map(seatingState.deskLayout.filter(item=>selectedDesks.has(item.id)).map(item=>[item.id,{x:item.x,y:item.y}]));
      const move=e=>{const point=gridPoint(e),snap=seatEl('#snapDesks').checked?10:1;seatingState.deskLayout.forEach(item=>{const origin=origins.get(item.id);if(origin){item.x=Math.max(0,Math.round((origin.x+point.x-start.x)/snap)*snap);item.y=Math.max(0,Math.round((origin.y+point.y-start.y)/snap)*snap)}});renderCustomLayoutV2()};
      const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);queueSave()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)
    };
    el.querySelector('.desk-resize').onpointerdown=event=>{
      if(!layoutEditing)return;event.preventDefault();event.stopPropagation();if(!selectedDesks.has(desk.id)){selectedDesks.clear();selectedDesks.add(desk.id);refreshDeskSelection()}
      pushDeskHistory();const chosen=seatingState.deskLayout.filter(item=>selectedDesks.has(item.id)),origins=new Map(chosen.map(item=>[item.id,{x:item.x,y:item.y,w:item.w,h:item.h}])),left=Math.min(...chosen.map(item=>item.x)),top=Math.min(...chosen.map(item=>item.y)),right=Math.max(...chosen.map(item=>item.x+item.w)),bottom=Math.max(...chosen.map(item=>item.y+item.h)),boxW=Math.max(1,right-left),boxH=Math.max(1,bottom-top),minimumX=Math.max(...chosen.map(item=>60/item.w)),minimumY=Math.max(...chosen.map(item=>45/item.h)),start=gridPoint(event);
      const move=e=>{const point=gridPoint(e),snap=seatEl('#snapDesks').checked?10:1,scaleX=Math.max(minimumX,(boxW+point.x-start.x)/boxW),scaleY=Math.max(minimumY,(boxH+point.y-start.y)/boxH);seatingState.deskLayout.forEach(item=>{const origin=origins.get(item.id);if(!origin)return;item.x=Math.max(0,Math.round((left+(origin.x-left)*scaleX)/snap)*snap);item.y=Math.max(0,Math.round((top+(origin.y-top)*scaleY)/snap)*snap);item.w=Math.max(60,Math.round(origin.w*scaleX/snap)*snap);item.h=Math.max(45,Math.round(origin.h*scaleY/snap)*snap)});renderCustomLayoutV2()};
      const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);queueSave()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)
    };
    seatingGrid.append(el)
  });
  const maxY=Math.max(480,...seatingState.deskLayout.map(d=>d.y+d.h+30));seatingGrid.style.minHeight=`${maxY}px`;
  seatingGrid.onpointerdown=event=>{
    if(!layoutEditing||event.target!==seatingGrid)return;event.preventDefault();const start=gridPoint(event),original=event.shiftKey?new Set(selectedDesks):new Set();if(!event.shiftKey)selectedDesks.clear();const box=document.createElement('div');box.className='desk-selection-box';seatingGrid.append(box);
    const move=e=>{const point=gridPoint(e),left=Math.min(start.x,point.x),top=Math.min(start.y,point.y),right=Math.max(start.x,point.x),bottom=Math.max(start.y,point.y);box.style.cssText=`left:${left}px;top:${top}px;width:${right-left}px;height:${bottom-top}px`;selectedDesks=new Set(original);seatingState.deskLayout.forEach(item=>{if(item.x<right&&item.x+item.w>left&&item.y<bottom&&item.y+item.h>top)selectedDesks.add(item.id)});refreshDeskSelection()};
    const up=()=>{box.remove();window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);refreshDeskSelection()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)
  }
}
function shuffleChart(){const open=seatingState.seats.map((_,i)=>i).filter(i=>!seatingState.locked[i]),names=open.map(i=>seatingState.seats[i]).filter(Boolean),arranged=arrangement(names,open.length);open.forEach((i,p)=>seatingState.seats[i]=arranged[p]||null);renderSeatingChart();queueSave()}
function createGroups(){const count=Number(seatEl('#seatingGroupCount').value)||2,names=shuffled(rosterNames()),groups=Array.from({length:count},()=>[]);names.forEach((name,i)=>groups[i%count].push(name));seatEl('#seatingGroupResults').innerHTML=groups.map((group,i)=>`<section><strong>Group ${i+1}</strong><p>${group.join('<br>')||'—'}</p></section>`).join('')}
function importRoster(file){const reader=new FileReader();reader.onload=()=>{let rows=String(reader.result||'').split(/\r?\n/).map(row=>row.split(',')[0].replace(/^\s*["']|["']\s*$/g,'').trim()).filter(Boolean);if(/^(student|name|student name)$/i.test(rows[0]||''))rows.shift();seatingRoster.value=rows.slice(0,100).join('\n');showToast(`${Math.min(rows.length,100)} students imported`);queueSave()};reader.readAsText(file)}
function downloadChart(){const custom=seatingState.layoutMode==='custom',scale=2,cellW=180,cellH=100,pad=50,maxX=custom?Math.max(700,...seatingState.deskLayout.map(d=>d.x+d.w+pad)):Math.max(700,seatingState.columns*cellW+pad*2),maxY=custom?Math.max(650,...seatingState.deskLayout.map(d=>d.y+d.h+190)):190+seatingState.rows*cellH,width=maxX,height=maxY,canvas=document.createElement('canvas');canvas.width=width*scale;canvas.height=height*scale;const c=canvas.getContext('2d');c.scale(scale,scale);c.fillStyle='#f4f8fc';c.fillRect(0,0,width,height);c.fillStyle='#173868';c.font='bold 28px sans-serif';c.textAlign='center';c.fillText(seatingClassName.value||'My Class',width/2,42);c.fillRect(width*.25,65,width*.5,38);c.fillStyle='#fff';c.font='bold 14px sans-serif';c.fillText('FRONT OF ROOM',width/2,90);seatingState.seats.forEach((name,i)=>{const desk=custom?seatingState.deskLayout[i]:null,row=Math.floor(i/seatingState.columns),col=i%seatingState.columns,x=custom?(desk?.x||0)+pad:pad+col*cellW,y=custom?(desk?.y||0)+125:125+row*cellH,w=custom?(desk?.w||98):cellW-16,h=custom?(desk?.h||68):cellH-16;c.save();c.translate(x+w/2,y+h/2);c.rotate(((desk?.rotation||0)*Math.PI)/180);c.fillStyle=name?'#fff':'#e8eef5';c.strokeStyle=seatingState.locked[i]?'#e6a700':'#b8c9dc';c.lineWidth=3;c.beginPath();c.roundRect(-w/2,-h/2,w,h,12);c.fill();c.stroke();c.fillStyle='#173868';c.font='bold 16px sans-serif';c.fillText(name||'Empty',0,6,w-20);c.restore()});const link=document.createElement('a');link.download=`${(seatingClassName.value||'seating-chart').replace(/[^a-z0-9]+/gi,'-')}.png`;link.href=canvas.toDataURL('image/png');link.click()}
function setStorage(mode){seatingStorageMode=mode;localStorage.setItem('glnSeatingStorageMode',mode);seatingLocalMode.classList.toggle('active',mode==='local');seatingGoogleMode.classList.toggle('active',mode==='google');const signed=Boolean(currentUser&&!currentUser.isAnonymous);seatingGoogleSignIn.hidden=mode!=='google'||signed;if(mode==='local')saveLocal();else if(signed)loadCloud();else initializeAccount()}
async function initializeAccount(){try{await initRaceFirebase();if(currentUser&&!currentUser.isAnonymous){seatingGoogleSignIn.hidden=true;await loadCloud()}else{seatingGoogleSignIn.hidden=false;seatingStorageStatus.textContent='Sign in to sync all classes across devices'}}catch{seatingGoogleSignIn.hidden=false;seatingStorageStatus.textContent='Google sync is not configured yet.'}}
async function signInGoogle(){seatingGoogleSignIn.disabled=true;try{await initRaceFirebase();const provider=new fb.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const credential=await fb.signInWithPopup(auth,provider);currentUser=credential.user;seatingGoogleSignIn.hidden=true;await loadCloud()}catch{seatingStorageStatus.textContent='Google sign-in was not completed.'}finally{seatingGoogleSignIn.disabled=false}}
async function loadCloud(){if(!currentUser||currentUser.isAnonymous)return;try{const snapshot=await fb.get(fb.ref(db,`seatingCharts/${currentUser.uid}`));if(snapshot.exists()){const data=snapshot.val();if(Array.isArray(data.classes)&&data.classes.length){seatingClasses=data.classes.map(normalize);activeClassId=data.activeClassId||seatingClasses[0].id;applyState(seatingClasses.find(c=>c.id===activeClassId)||seatingClasses[0])}}else await saveCloud();seatingStorageStatus.textContent=`Synced with ${currentUser.email||'Google account'}`;seatingStorageStatus.classList.add('synced')}catch{seatingStorageStatus.textContent='Could not load the cloud copy.'}}
function selectedDeskIndexes(){return seatingState.deskLayout.map((desk,index)=>selectedDesks.has(desk.id)?index:-1).filter(index=>index>=0)}
function addDesk(){pushDeskHistory();if(seatingState.layoutMode!=='custom')gridToCustom();const index=seatingState.deskLayout.length,seating=seatingState.deskLayout;const desk={id:`desk-${Date.now()}-${index}`,x:30+(index%5)*120,y:30+Math.floor(index/5)*90,w:98,h:68,rotation:0};seating.push(desk);seatingState.seats.push(null);seatingState.locked.push(false);selectedDesks=new Set([desk.id]);layoutEditing=true;renderSeatingChart();queueSave()}
function deleteSelectedDesks(){const indexes=selectedDeskIndexes().sort((a,b)=>b-a);if(!indexes.length){showToast('Select a desk first');return}pushDeskHistory();indexes.forEach(index=>{seatingState.deskLayout.splice(index,1);seatingState.seats.splice(index,1);seatingState.locked.splice(index,1)});selectedDesks.clear();renderSeatingChart();queueSave()}
function duplicateSelectedDesk(){const index=selectedDeskIndexes()[0];if(index===undefined){showToast('Select a desk first');return}pushDeskHistory();const source=seatingState.deskLayout[index],desk={...source,id:`desk-${Date.now()}`,x:source.x+20,y:source.y+20};seatingState.deskLayout.push(desk);seatingState.seats.push(null);seatingState.locked.push(false);selectedDesks=new Set([desk.id]);renderSeatingChart();queueSave()}
function rotateSelected(){const indexes=selectedDeskIndexes();if(!indexes.length){showToast('Select a desk first');return}pushDeskHistory();indexes.forEach(index=>seatingState.deskLayout[index].rotation=((seatingState.deskLayout[index].rotation||0)+15)%360);renderSeatingChart();queueSave()}
function resetToGrid(){pushDeskHistory();seatingState.layoutMode='grid';layoutEditing=false;selectedDesks.clear();const count=seatingState.rows*seatingState.columns;seatingState.seats=seatingState.seats.slice(0,count);while(seatingState.seats.length<count)seatingState.seats.push(null);seatingState.locked=seatingState.locked.slice(0,count);while(seatingState.locked.length<count)seatingState.locked.push(false);renderSeatingChart();queueSave()}
function toggleLayoutEditor(){if(seatingState.layoutMode!=='custom'){pushDeskHistory();gridToCustom();layoutEditing=true}else layoutEditing=!layoutEditing;selectedDesks.clear();renderSeatingChart();queueSave()}
function undoDeskEdit(){if(!deskUndo.length)return;deskRedo.push(deskSnapshot());restoreDeskSnapshot(deskUndo.pop())}
function redoDeskEdit(){if(!deskRedo.length)return;deskUndo.push(deskSnapshot());restoreDeskSnapshot(deskRedo.pop())}
const saved=JSON.parse(localStorage.getItem('glnSeatingClasses')||'null');if(saved?.classes?.length){seatingClasses=saved.classes.map(normalize);activeClassId=saved.activeClassId||seatingClasses[0].id}else{const legacy=JSON.parse(localStorage.getItem('glnSeatingChart')||'null'),initial=normalize(legacy||{className:'My Class',roster:defaultRoster});seatingClasses=[initial];activeClassId=initial.id}applyState(seatingClasses.find(c=>c.id===activeClassId)||seatingClasses[0]);
seatingClassSelect.onchange=()=>{const selectedClassId=seatingClassSelect.value;saveLocal();applyState(seatingClasses.find(c=>c.id===selectedClassId)||seatingClasses[0]);queueSave()};seatEl('#newSeatingClass').onclick=()=>{saveLocal();const item=blankClass(`Class ${seatingClasses.length+1}`);seatingClasses.push(item);applyState(item);queueSave()};seatEl('#deleteSeatingClass').onclick=()=>{if(seatingClasses.length===1){showToast('Keep at least one class');return}if(!confirm(`Delete ${seatingState.className}?`))return;seatingClasses=seatingClasses.filter(c=>c.id!==activeClassId);applyState(seatingClasses[0]);queueSave()};
seatEl('#buildSeating').onclick=buildChart;seatEl('#shuffleSeating').onclick=shuffleChart;seatEl('#flipSeating').onclick=()=>{seatingState.flipped=!seatingState.flipped;renderSeatingChart();queueSave()};seatEl('#editDeskLayout').onclick=toggleLayoutEditor;seatEl('#resetDeskGrid').onclick=resetToGrid;seatEl('#addDesk').onclick=addDesk;seatEl('#deleteDesk').onclick=deleteSelectedDesks;seatEl('#duplicateDesk').onclick=duplicateSelectedDesk;seatEl('#rotateDesk').onclick=rotateSelected;seatEl('#undoDesk').onclick=undoDeskEdit;seatEl('#redoDesk').onclick=redoDeskEdit;seatEl('#makeSeatingGroups').onclick=createGroups;seatEl('#importSeatingRoster').onclick=()=>seatEl('#seatingFileInput').click();seatEl('#seatingFileInput').onchange=e=>{if(e.target.files[0])importRoster(e.target.files[0]);e.target.value=''};seatEl('#downloadSeating').onclick=downloadChart;seatingLocalMode.onclick=()=>setStorage('local');seatingGoogleMode.onclick=()=>setStorage('google');seatingGoogleSignIn.onclick=signInGoogle;seatEl('#seatingFullscreen').onclick=()=>{if(!document.fullscreenElement)seatEl('#seatingPanel').requestFullscreen?.();else document.exitFullscreen?.()};seatEl('#printSeating').onclick=()=>{document.body.classList.add('print-seating');window.print()};window.addEventListener('afterprint',()=>document.body.classList.remove('print-seating'));[seatingClassName,seatingRoster,seatEl('#seatingKeepApart'),seatEl('#seatingNearFront'),seatEl('#seatingGroupA'),seatEl('#seatingGroupB')].forEach(input=>input.addEventListener('change',queueSave));seatEl('#seatingAlternateGender').onchange=queueSave;setStorage(seatingStorageMode);window.renderSeatingChart=renderSeatingChart;
