const seatEl=id=>document.querySelector(id);
const seatingClassName=seatEl('#seatingClassName'),seatingClassSelect=seatEl('#seatingClassSelect'),seatingRoster=seatEl('#seatingRoster'),seatingRows=seatEl('#seatingRows'),seatingColumns=seatEl('#seatingColumns'),seatingGrid=seatEl('#seatingGrid'),seatingBoard=seatEl('#seatingBoard'),seatingChartName=seatEl('#seatingChartName'),seatingLocalMode=seatEl('#seatingLocalMode'),seatingGoogleMode=seatEl('#seatingGoogleMode'),seatingGoogleSignIn=seatEl('#seatingGoogleSignIn'),seatingStorageStatus=seatEl('#seatingStorageStatus');
const defaultRoster=['Alex','Maria','Saw Htoo','Naw Paw','Jordan','Taylor'];
const blankClass=(name='My Class')=>({id:`class-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,className:name,roster:[],rows:5,columns:6,seats:[],locked:[],flipped:false,layoutMode:'custom',deskLayout:[],roomWidth:760,roomHeight:520,roomPreset:'medium',snapGrid:true,smartGuides:true,preventOverlap:false,rules:{keepApart:'',nearFront:'',alternate:false,groupA:'',groupB:''},updatedAt:Date.now()});
let seatingClasses=[],activeClassId='',seatingState=blankClass(),seatingStorageMode=localStorage.getItem('glnSeatingStorageMode')||'local',seatingSaveTimer=null,seatingDraggedIndex=null,selectedDesks=new Set(),deskUndo=[],deskRedo=[],layoutEditing=false,currentRoomScale=1,manualRoomScale=null,deskClipboard=null;
for(let value=2;value<=10;value++){seatingRows.add(new Option(String(value),String(value)));seatingColumns.add(new Option(String(value),String(value)));seatEl('#seatingGroupCount').add(new Option(String(value),String(value)))}
function lines(value){return String(value||'').split(/\r?\n/).map(v=>v.trim()).filter(Boolean)}
function rosterNames(){return lines(seatingRoster.value).slice(0,100)}
function readRules(){return{keepApart:seatEl('#seatingKeepApart').value,nearFront:seatEl('#seatingNearFront').value,alternate:seatEl('#seatingAlternateGender').checked,groupA:seatEl('#seatingGroupA').value,groupB:seatEl('#seatingGroupB').value}}
function capture(){seatingState={...seatingState,className:seatingClassName.value.trim()||'My Class',roster:rosterNames(),rows:Number(seatingRows.value)||5,columns:Number(seatingColumns.value)||6,roomWidth:Math.max(500,Math.min(2000,Number(seatEl('#roomWidth').value)||760)),roomHeight:Math.max(360,Math.min(1400,Number(seatEl('#roomHeight').value)||520)),roomPreset:seatEl('#roomPreset').value,snapGrid:seatEl('#snapDesks').checked,smartGuides:seatEl('#smartGuides').checked,preventOverlap:false,rules:readRules(),updatedAt:Date.now()};return seatingState}
function normalize(data={}){const base=blankClass();return{...base,...data,id:String(data.id||base.id),className:String(data.className||'My Class').slice(0,50),roster:Array.isArray(data.roster)?data.roster.slice(0,100):[],rows:Math.max(2,Math.min(10,Number(data.rows)||5)),columns:Math.max(2,Math.min(10,Number(data.columns)||6)),seats:Array.isArray(data.seats)?data.seats.slice(0,100):[],locked:Array.isArray(data.locked)?data.locked.slice(0,100):[],layoutMode:'custom',deskLayout:Array.isArray(data.deskLayout)?data.deskLayout:[],roomWidth:Math.max(500,Math.min(2000,Number(data.roomWidth)||760)),roomHeight:Math.max(360,Math.min(1400,Number(data.roomHeight)||520)),snapGrid:data.snapGrid!==false,smartGuides:data.smartGuides!==false,preventOverlap:false,rules:{...base.rules,...(data.rules||{})}}}
function refreshMenu(){seatingClassSelect.innerHTML='';seatingClasses.forEach(item=>seatingClassSelect.add(new Option(item.className,item.id)));seatingClassSelect.value=activeClassId;const list=seatEl('#seatingClassList');if(list){list.innerHTML='';seatingClasses.forEach(item=>{const button=document.createElement('button');button.type='button';button.textContent=item.className;button.classList.toggle('active',item.id===activeClassId);button.setAttribute('aria-current',item.id===activeClassId?'true':'false');button.onclick=()=>switchSeatingClass(item.id);list.append(button)})}const source=seatEl('#seatingLayoutSource'),previous=source.value;source.innerHTML='';seatingClasses.filter(item=>item.id!==activeClassId).forEach(item=>source.add(new Option(item.className,item.id)));if([...source.options].some(option=>option.value===previous))source.value=previous;seatEl('#useClassLayout').disabled=!source.options.length;updateRosterCount()}
function switchSeatingClass(id){if(id===activeClassId)return;saveLocal();manualRoomScale=null;applyState(seatingClasses.find(item=>item.id===id)||seatingClasses[0]);queueSave();seatEl('#seatingPanel').classList.remove('classes-open')}
function updateRosterCount(){const count=rosterNames().length,label=seatEl('#seatingRosterCount');if(label)label.textContent=`${count} student${count===1?'':'s'}`}
function applyState(data){seatingState=normalize(data);activeClassId=seatingState.id;selectedDesks.clear();deskUndo=[];deskRedo=[];seatingClassName.value=seatingState.className;seatingRoster.value=seatingState.roster.join('\n');seatingRows.value=seatingState.rows;seatingColumns.value=seatingState.columns;seatEl('#roomWidth').value=seatingState.roomWidth;seatEl('#roomHeight').value=seatingState.roomHeight;seatEl('#roomPreset').value=seatingState.roomPreset||'custom';seatEl('#snapDesks').checked=seatingState.snapGrid;seatEl('#smartGuides').checked=seatingState.smartGuides;seatEl('#preventDeskOverlap').checked=false;seatEl('#seatingKeepApart').value=seatingState.rules.keepApart;seatEl('#seatingNearFront').value=seatingState.rules.nearFront;seatEl('#seatingAlternateGender').checked=seatingState.rules.alternate;seatEl('#seatingGroupA').value=seatingState.rules.groupA;seatEl('#seatingGroupB').value=seatingState.rules.groupB;if(!seatingState.seats.length&&seatingState.roster.length)seatingState.seats=seatingState.roster.slice();if(!seatingState.deskLayout.length&&seatingState.seats.length){gridToCustom();const rows=Math.ceil(seatingState.seats.length/(seatingState.columns||6));seatingState.roomHeight=Math.max(seatingState.roomHeight,Math.min(1400,rows*90+50));seatEl('#roomHeight').value=seatingState.roomHeight}refreshMenu();renderSeatingChart()}
function upsert(){capture();const index=seatingClasses.findIndex(item=>item.id===activeClassId);if(index<0)seatingClasses.push(seatingState);else seatingClasses[index]=structuredClone(seatingState);refreshMenu()}
function payload(){return{activeClassId,classes:seatingClasses,updatedAt:Date.now()}}
function saveLocal(){upsert();localStorage.setItem('glnSeatingClasses',JSON.stringify(payload()));seatingStorageStatus.textContent='Saved locally on this device';seatingStorageStatus.classList.add('synced')}
async function saveCloud(){if(seatingStorageMode!=='google'||!currentUser||currentUser.isAnonymous)return;try{upsert();await fb.set(fb.ref(db,`seatingCharts/${currentUser.uid}`),payload());seatingStorageStatus.textContent=`Synced with ${currentUser.email||'Google account'}`;seatingStorageStatus.classList.add('synced')}catch{seatingStorageStatus.textContent='Could not sync. Your local copy is still saved.';seatingStorageStatus.classList.remove('synced')}}
function queueSave(){saveLocal();clearTimeout(seatingSaveTimer);if(seatingStorageMode==='google')seatingSaveTimer=setTimeout(saveCloud,600)}
function shuffled(items){const list=[...items];for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function arrangement(names,count){const rules=readRules(),front=new Set(lines(rules.nearFront)),aSet=new Set(lines(rules.groupA)),bSet=new Set(lines(rules.groupB));let pool=shuffled(names),ordered=[...pool.filter(name=>front.has(name))];pool=pool.filter(name=>!front.has(name));if(rules.alternate){const a=shuffled(pool.filter(name=>aSet.has(name))),b=shuffled(pool.filter(name=>bSet.has(name))),other=pool.filter(name=>!aSet.has(name)&&!bSet.has(name));while(a.length||b.length){if(a.length)ordered.push(a.shift());if(b.length)ordered.push(b.shift())}ordered.push(...shuffled(other))}else ordered.push(...pool);while(ordered.length<count)ordered.push(null);const pairs=lines(rules.keepApart).map(row=>row.split(',').map(v=>v.trim())).filter(pair=>pair.length===2&&pair[0]&&pair[1]);for(let pass=0;pass<6;pass++)pairs.forEach(([a,b])=>{const ai=ordered.indexOf(a),bi=ordered.indexOf(b);if(ai<0||bi<0)return;const distance=i=>Math.abs(Math.floor(ai/seatingState.columns)-Math.floor(i/seatingState.columns))+Math.abs(ai%seatingState.columns-i%seatingState.columns);if(distance(bi)<=1){const far=ordered.findIndex((_,i)=>i!==ai&&i!==bi&&!seatingState.locked[i]&&distance(i)>1);if(far>=0)[ordered[bi],ordered[far]]=[ordered[far],ordered[bi]]}});return ordered.slice(0,count)}
function buildChart(){capture();if(seatingState.layoutMode==='custom'){pushDeskHistory();while(seatingState.deskLayout.length<seatingState.roster.length){const index=seatingState.deskLayout.length;let spot=findOpenDeskSpot(98,68);while(!spot&&seatingState.roomHeight<1400){seatingState.roomHeight=Math.min(1400,seatingState.roomHeight+100);spot=findOpenDeskSpot(98,68)}if(!spot){showToast('Room is full — enlarge it to add more desks');break}seatingState.deskLayout.push({id:`desk-${Date.now()}-${index}`,...spot,w:98,h:68,rotation:0});seatingState.locked.push(false)}seatEl('#roomHeight').value=Math.round(seatingState.roomHeight);seatingState.seats=seatingState.roster.slice(0,seatingState.deskLayout.length);while(seatingState.seats.length<seatingState.deskLayout.length)seatingState.seats.push(null);renderSeatingChart();queueSave();showToast('Names updated — custom layout preserved');return}const count=seatingState.rows*seatingState.columns;if(seatingState.roster.length>count)showToast(`Add more seats for ${seatingState.roster.length-count} students`);seatingState.deskLayout=[];seatingState.locked=Array(count).fill(false);seatingState.seats=arrangement(seatingState.roster.slice(0,count),count);renderSeatingChart();queueSave()}
function renderSeatingChart(){seatingChartName.textContent=seatingClassName.value.trim()||seatingState.className;seatingBoard.classList.toggle('flipped',seatingState.flipped);seatingBoard.classList.toggle('custom-layout',seatingState.layoutMode==='custom');seatingBoard.classList.toggle('editing',layoutEditing);seatEl('#editDeskLayout').textContent=layoutEditing?'Finish editing':'Edit layout';seatEl('#buildSeating').textContent=seatingState.layoutMode==='custom'?'Update student names':'Build seating chart';updateDeskInspector();if(seatingState.layoutMode==='custom'){renderCustomLayoutV2();return}const count=seatingState.rows*seatingState.columns;seatingState.seats=seatingState.seats.slice(0,count);while(seatingState.seats.length<count)seatingState.seats.push(null);seatingState.locked=seatingState.locked.slice(0,count);while(seatingState.locked.length<count)seatingState.locked.push(false);seatingGrid.style.gridTemplateColumns=`repeat(${seatingState.columns},minmax(88px,1fr))`;seatingGrid.innerHTML='';const rows=[...Array(seatingState.rows).keys()];if(seatingState.flipped)rows.reverse();rows.forEach(row=>{for(let column=0;column<seatingState.columns;column++){const index=row*seatingState.columns+column,name=seatingState.seats[index],seat=document.createElement('article');seat.className=`student-seat${name?'':' empty'}${seatingState.locked[index]?' locked':''}`;seat.draggable=Boolean(name&&!seatingState.locked[index]);seat.innerHTML=`<span class="seat-number">${index+1}</span><span>${name||'Empty'}</span>`;if(name){const lock=document.createElement('button');lock.type='button';lock.className='seat-lock';lock.textContent=seatingState.locked[index]?'🔒':'🔓';lock.onclick=e=>{e.stopPropagation();seatingState.locked[index]=!seatingState.locked[index];renderSeatingChart();queueSave()};seat.append(lock)}seat.ondragstart=()=>{seatingDraggedIndex=index;seat.classList.add('dragging')};seat.ondragend=()=>{seatingDraggedIndex=null;seat.classList.remove('dragging')};seat.ondragover=e=>{if(seatingDraggedIndex!==null&&!seatingState.locked[index]){e.preventDefault();seat.classList.add('drag-over')}};seat.ondragleave=()=>seat.classList.remove('drag-over');seat.ondrop=e=>{e.preventDefault();seat.classList.remove('drag-over');if(seatingDraggedIndex===null||seatingState.locked[index]||seatingState.locked[seatingDraggedIndex])return;[seatingState.seats[index],seatingState.seats[seatingDraggedIndex]]=[seatingState.seats[seatingDraggedIndex],seatingState.seats[index]];renderSeatingChart();queueSave()};seatingGrid.append(seat)}});requestAnimationFrame(updateRoomScale)}
function gridToCustom(){const cols=seatingState.columns||6;seatingState.deskLayout=seatingState.seats.map((_,i)=>({id:`desk-${Date.now()}-${i}`,x:25+(i%cols)*115,y:20+Math.floor(i/cols)*90,w:98,h:68,rotation:0}));seatingState.layoutMode='custom'}
function deskSnapshot(){return JSON.stringify({deskLayout:seatingState.deskLayout,seats:seatingState.seats,locked:seatingState.locked,layoutMode:seatingState.layoutMode,roomWidth:seatingState.roomWidth,roomHeight:seatingState.roomHeight,roomPreset:seatingState.roomPreset})}
function pushDeskHistory(){deskUndo.push(deskSnapshot());if(deskUndo.length>40)deskUndo.shift();deskRedo=[]}
function restoreDeskSnapshot(value){const data=JSON.parse(value);seatingState.deskLayout=data.deskLayout;seatingState.seats=data.seats;seatingState.locked=data.locked;seatingState.layoutMode=data.layoutMode;seatingState.roomWidth=data.roomWidth||seatingState.roomWidth;seatingState.roomHeight=data.roomHeight||seatingState.roomHeight;seatingState.roomPreset=data.roomPreset||'custom';seatEl('#roomWidth').value=seatingState.roomWidth;seatEl('#roomHeight').value=seatingState.roomHeight;seatEl('#roomPreset').value=seatingState.roomPreset;selectedDesks.clear();renderSeatingChart();queueSave()}
function renderCustomLayout(){seatingGrid.innerHTML='';seatingGrid.style.gridTemplateColumns='none';seatingState.deskLayout.forEach((desk,index)=>{const name=seatingState.seats[index],el=document.createElement('article');el.className=`student-seat custom-desk${name?'':' empty'}${selectedDesks.has(desk.id)?' selected':''}`;el.dataset.deskId=desk.id;el.style.cssText=`left:${desk.x}px;top:${desk.y}px;width:${desk.w}px;height:${desk.h}px;transform:rotate(${desk.rotation||0}deg)`;el.innerHTML=`<span class="seat-number">${index+1}</span><span>${name||'Empty'}</span><i class="desk-resize" aria-hidden="true"></i>`;el.onpointerdown=e=>{if(!layoutEditing||e.target.classList.contains('desk-resize'))return;e.preventDefault();if(e.shiftKey){if(selectedDesks.has(desk.id))selectedDesks.delete(desk.id);else selectedDesks.add(desk.id);renderCustomLayout();return}if(!selectedDesks.has(desk.id)){selectedDesks.clear();selectedDesks.add(desk.id)}pushDeskHistory();const startX=e.clientX,startY=e.clientY,origins=new Map(seatingState.deskLayout.filter(d=>selectedDesks.has(d.id)).map(d=>[d.id,{x:d.x,y:d.y}]));const move=event=>{const snap=seatEl('#snapDesks').checked?10:1;seatingState.deskLayout.forEach(d=>{const origin=origins.get(d.id);if(origin){d.x=Math.max(0,Math.round((origin.x+event.clientX-startX)/snap)*snap);d.y=Math.max(0,Math.round((origin.y+event.clientY-startY)/snap)*snap)}});renderCustomLayout()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);queueSave()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)};el.querySelector('.desk-resize').onpointerdown=e=>{if(!layoutEditing)return;e.preventDefault();e.stopPropagation();pushDeskHistory();selectedDesks.clear();selectedDesks.add(desk.id);const sx=e.clientX,sy=e.clientY,ow=desk.w,oh=desk.h;const move=event=>{const snap=seatEl('#snapDesks').checked?10:1;desk.w=Math.max(60,Math.round((ow+event.clientX-sx)/snap)*snap);desk.h=Math.max(45,Math.round((oh+event.clientY-sy)/snap)*snap);renderCustomLayout()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);queueSave()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)};seatingGrid.append(el)});const maxY=Math.max(480,...seatingState.deskLayout.map(d=>d.y+d.h+30));seatingGrid.style.minHeight=`${maxY}px`}
function gridPoint(event){const box=seatingGrid.getBoundingClientRect();return{x:(event.clientX-box.left)/currentRoomScale,y:(event.clientY-box.top)/currentRoomScale}}
function refreshDeskSelection(){seatingGrid.querySelectorAll('.custom-desk').forEach(el=>el.classList.toggle('selected',selectedDesks.has(el.dataset.deskId)));updateDeskInspector()}
function updateDeskInspector(){const count=selectedDesks.size,title=seatEl('#deskInspectorTitle'),hint=seatEl('#deskInspectorHint'),status=seatEl('#seatingSelectionStatus');if(!title)return;if(!count){title.textContent=layoutEditing?'Room':'Room view';hint.textContent=layoutEditing?'Select a desk or drag across the room to select several.':'Choose Edit layout to move desks.';if(status)status.textContent=layoutEditing?'Editing room':'Room view'}else if(count===1){const index=selectedDeskIndexes()[0],name=seatingState.seats[index]||'Empty desk';title.textContent=name;hint.textContent='Double-click the desk to change its name.';if(status)status.textContent=`1 desk selected`}else{title.textContent=`${count} desks`;hint.textContent='Move, resize, rotate, or delete them together.';if(status)status.textContent=`${count} desks selected`}['duplicateDesk','rotateDesk','deleteDesk'].forEach(id=>{const button=seatEl(`#${id}`);if(button)button.disabled=!count})}
const DESK_GAP=10;
function deskPolygon(desk,gap=0){const angle=(Number(desk.rotation)||0)*Math.PI/180,cx=desk.x+desk.w/2,cy=desk.y+desk.h/2,hw=(desk.w+gap)/2,hh=(desk.h+gap)/2,cos=Math.cos(angle),sin=Math.sin(angle);return[[-hw,-hh],[hw,-hh],[hw,hh],[-hw,hh]].map(([x,y])=>({x:cx+x*cos-y*sin,y:cy+x*sin+y*cos}))}
function polygonAxes(points){return points.map((point,index)=>{const next=points[(index+1)%points.length],x=-(next.y-point.y),y=next.x,length=Math.hypot(x,y)||1;return{x:x/length,y:y/length}})}
function polygonProjection(points,axis){const values=points.map(point=>point.x*axis.x+point.y*axis.y);return{min:Math.min(...values),max:Math.max(...values)}}
function overlaps(a,b,gap=DESK_GAP){const first=deskPolygon(a,gap),second=deskPolygon(b,gap),axes=[...polygonAxes(first),...polygonAxes(second)];return axes.every(axis=>{const x=polygonProjection(first,axis),y=polygonProjection(second,axis);return x.max>y.min&&y.max>x.min})}
function insideRoom(desk){return deskPolygon(desk).every(point=>point.x>=0&&point.y>=0&&point.x<=seatingState.roomWidth&&point.y<=seatingState.roomHeight)}
function validDeskChanges(changes){const changedIds=new Set(changes.keys()),layout=seatingState.deskLayout.map(desk=>changes.get(desk.id)||desk);return !layout.some(desk=>changedIds.has(desk.id)&&!insideRoom(desk))}
let collisionFlashTimer=0;
function flashDeskCollision(ids=selectedDesks){clearTimeout(collisionFlashTimer);seatingGrid.querySelectorAll('.custom-desk').forEach(element=>element.classList.toggle('collision-blocked',ids.has(element.dataset.deskId)));collisionFlashTimer=setTimeout(()=>seatingGrid.querySelectorAll('.collision-blocked').forEach(element=>element.classList.remove('collision-blocked')),260)}
function applyDeskChanges(changes){if(!validDeskChanges(changes))return false;changes.forEach((next,id)=>Object.assign(seatingState.deskLayout.find(item=>item.id===id),next));return true}
function clearSmartGuides(){seatingGrid.querySelectorAll('.smart-guide').forEach(line=>line.remove())}
function drawSmartGuides(guides=[]){clearSmartGuides();guides.forEach(guide=>{const line=document.createElement('i');line.className=`smart-guide ${guide.axis==='x'?'vertical':'horizontal'}`;if(guide.axis==='x')line.style.left=`${guide.value}px`;else line.style.top=`${guide.value}px`;seatingGrid.append(line)})}
function moveDeskGroup(origins,dx,dy,disableGuides=false){const selected=seatingState.deskLayout.filter(item=>origins.has(item.id));let moveX=dx,moveY=dy,guides=[];if(seatEl('#snapDesks').checked){moveX=Math.round(moveX/10)*10;moveY=Math.round(moveY/10)*10}if(seatEl('#smartGuides').checked&&!disableGuides){const left=Math.min(...selected.map(item=>origins.get(item.id).x))+moveX,top=Math.min(...selected.map(item=>origins.get(item.id).y))+moveY,right=Math.max(...selected.map(item=>origins.get(item.id).x+item.w))+moveX,bottom=Math.max(...selected.map(item=>origins.get(item.id).y+item.h))+moveY,centerX=(left+right)/2,centerY=(top+bottom)/2;let bestX={d:7},bestY={d:7};seatingState.deskLayout.filter(item=>!origins.has(item.id)).forEach(other=>{[other.x,other.x+other.w,other.x+other.w/2].forEach(target=>[left,right,centerX].forEach(value=>{const difference=target-value;if(Math.abs(difference)<Math.abs(bestX.d))bestX={d:difference,value:target}}));[other.y,other.y+other.h,other.y+other.h/2].forEach(target=>[top,bottom,centerY].forEach(value=>{const difference=target-value;if(Math.abs(difference)<Math.abs(bestY.d))bestY={d:difference,value:target}}))});if(bestX.value!==undefined){moveX+=bestX.d;guides.push({axis:'x',value:bestX.value})}if(bestY.value!==undefined){moveY+=bestY.d;guides.push({axis:'y',value:bestY.value})}}const makeChanges=(x,y)=>new Map(selected.map(item=>{const origin=origins.get(item.id);return[item.id,{...item,x:origin.x+x,y:origin.y+y}]}));if(applyDeskChanges(makeChanges(moveX,moveY)))return guides;const xOnly=makeChanges(moveX,0),yOnly=makeChanges(0,moveY),xValid=validDeskChanges(xOnly),yValid=validDeskChanges(yOnly);if(xValid||yValid){if(xValid&&(!yValid||Math.abs(moveX)>=Math.abs(moveY)))applyDeskChanges(xOnly);else applyDeskChanges(yOnly);flashDeskCollision();return[]}let low=0,high=1,best=null;for(let pass=0;pass<9;pass++){const mid=(low+high)/2,candidate=makeChanges(moveX*mid,moveY*mid);if(validDeskChanges(candidate)){best=candidate;low=mid}else high=mid}if(best)applyDeskChanges(best);flashDeskCollision();return[]}
function resizeDeskGroup(origins,left,top,boxW,boxH,minimumX,minimumY,dx,dy){const snap=seatEl('#snapDesks').checked?10:1,makeChanges=factor=>{const scaleX=Math.max(minimumX,(boxW+dx*factor)/boxW),scaleY=Math.max(minimumY,(boxH+dy*factor)/boxH),changes=new Map();seatingState.deskLayout.forEach(item=>{const origin=origins.get(item.id);if(!origin)return;changes.set(item.id,{...item,x:Math.round((left+(origin.x-left)*scaleX)/snap)*snap,y:Math.round((top+(origin.y-top)*scaleY)/snap)*snap,w:Math.max(60,Math.round(origin.w*scaleX/snap)*snap),h:Math.max(45,Math.round(origin.h*scaleY/snap)*snap)})});return changes},full=makeChanges(1);if(applyDeskChanges(full))return;let low=0,high=1,best=null;for(let pass=0;pass<9;pass++){const mid=(low+high)/2,candidate=makeChanges(mid);if(validDeskChanges(candidate)){best=candidate;low=mid}else high=mid}if(best)applyDeskChanges(best);flashDeskCollision()}
function renderCustomLayoutV2(){
  seatingGrid.innerHTML='';seatingGrid.style.gridTemplateColumns='none';seatingGrid.style.width=`${seatingState.roomWidth}px`;seatingGrid.style.height=`${seatingState.roomHeight}px`;seatingGrid.style.minHeight=`${seatingState.roomHeight}px`;
  seatingState.deskLayout.forEach((desk,index)=>{
    const name=seatingState.seats[index],el=document.createElement('article');
    el.className=`student-seat custom-desk${name?'':' empty'}${selectedDesks.has(desk.id)?' selected':''}`;el.dataset.deskId=desk.id;
    el.style.cssText=`left:${desk.x}px;top:${desk.y}px;width:${desk.w}px;height:${desk.h}px;transform:rotate(${desk.rotation||0}deg)`;
    el.innerHTML=`<span class="seat-number">${index+1}</span><span>${name||'Empty'}</span><i class="desk-resize" aria-label="Resize selected desks"></i>`;
    el.ondblclick=event=>{event.preventDefault();event.stopPropagation();const entered=prompt('Student name for this desk:',seatingState.seats[index]||'');if(entered===null)return;pushDeskHistory();const studentName=entered.trim();seatingState.seats[index]=studentName||null;if(studentName&&!seatingState.roster.includes(studentName)){seatingState.roster.push(studentName);seatingRoster.value=seatingState.roster.join('\n')}renderCustomLayoutV2();queueSave()};
    el.onpointerdown=event=>{
      if(!layoutEditing||event.target.classList.contains('desk-resize'))return;event.preventDefault();event.stopPropagation();
      if(event.shiftKey){selectedDesks.has(desk.id)?selectedDesks.delete(desk.id):selectedDesks.add(desk.id);refreshDeskSelection();return}
      if(!selectedDesks.has(desk.id)){selectedDesks.clear();selectedDesks.add(desk.id);refreshDeskSelection()}
      pushDeskHistory();const start=gridPoint(event),origins=new Map(seatingState.deskLayout.filter(item=>selectedDesks.has(item.id)).map(item=>[item.id,{x:item.x,y:item.y}]));
      const move=e=>{const point=gridPoint(e),guides=moveDeskGroup(origins,point.x-start.x,point.y-start.y,e.altKey);renderCustomLayoutV2();drawSmartGuides(guides)};
      const up=()=>{clearSmartGuides();window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);queueSave()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)
    };
    el.querySelector('.desk-resize').onpointerdown=event=>{
      if(!layoutEditing)return;event.preventDefault();event.stopPropagation();if(!selectedDesks.has(desk.id)){selectedDesks.clear();selectedDesks.add(desk.id);refreshDeskSelection()}
      pushDeskHistory();const chosen=seatingState.deskLayout.filter(item=>selectedDesks.has(item.id)),origins=new Map(chosen.map(item=>[item.id,{x:item.x,y:item.y,w:item.w,h:item.h}])),left=Math.min(...chosen.map(item=>item.x)),top=Math.min(...chosen.map(item=>item.y)),right=Math.max(...chosen.map(item=>item.x+item.w)),bottom=Math.max(...chosen.map(item=>item.y+item.h)),boxW=Math.max(1,right-left),boxH=Math.max(1,bottom-top),minimumX=Math.max(...chosen.map(item=>60/item.w)),minimumY=Math.max(...chosen.map(item=>45/item.h)),start=gridPoint(event);
      const move=e=>{const point=gridPoint(e);resizeDeskGroup(origins,left,top,boxW,boxH,minimumX,minimumY,point.x-start.x,point.y-start.y);renderCustomLayoutV2()};
      const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);queueSave()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)
    };
    seatingGrid.append(el)
  });
  seatingGrid.onpointerdown=event=>{
    if(!layoutEditing||event.target!==seatingGrid)return;event.preventDefault();const start=gridPoint(event),original=event.shiftKey?new Set(selectedDesks):new Set();if(!event.shiftKey)selectedDesks.clear();const box=document.createElement('div');box.className='desk-selection-box';seatingGrid.append(box);
    const move=e=>{const point=gridPoint(e),left=Math.min(start.x,point.x),top=Math.min(start.y,point.y),right=Math.max(start.x,point.x),bottom=Math.max(start.y,point.y);box.style.cssText=`left:${left}px;top:${top}px;width:${right-left}px;height:${bottom-top}px`;selectedDesks=new Set(original);seatingState.deskLayout.forEach(item=>{if(item.x<right&&item.x+item.w>left&&item.y<bottom&&item.y+item.h>top)selectedDesks.add(item.id)});refreshDeskSelection()};
    const up=()=>{box.remove();window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);refreshDeskSelection()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)
  };requestAnimationFrame(updateRoomScale)
}
function updateRoomScale(){const wrap=seatEl('#seatingPrintArea');if(!wrap||wrap.clientWidth<1)return;seatingBoard.style.zoom='';seatingGrid.style.zoom='';const naturalWidth=seatingState.layoutMode==='custom'?seatingState.roomWidth:Math.max(560,seatingGrid.scrollWidth),naturalHeight=(seatingState.layoutMode==='custom'?seatingState.roomHeight:seatingGrid.scrollHeight)+100,fit=Math.max(.25,Math.min(1.6,(wrap.clientWidth-42)/naturalWidth,(wrap.clientHeight-42)/naturalHeight));currentRoomScale=Math.max(.25,Math.min(2.5,manualRoomScale??fit));seatingBoard.style.zoom=String(currentRoomScale);const label=seatEl('#seatingZoomLabel');if(label)label.textContent=`${Math.round(currentRoomScale*100)}%`}
function fitSeatingRoom(){manualRoomScale=null;updateRoomScale()}
function changeSeatingZoom(amount){manualRoomScale=Math.max(.25,Math.min(2.5,(manualRoomScale??currentRoomScale)+amount));updateRoomScale()}
function shuffleChart(){const open=seatingState.seats.map((_,i)=>i).filter(i=>!seatingState.locked[i]),names=open.map(i=>seatingState.seats[i]).filter(Boolean),arranged=arrangement(names,open.length);open.forEach((i,p)=>seatingState.seats[i]=arranged[p]||null);renderSeatingChart();queueSave()}
function createGroups(){const count=Number(seatEl('#seatingGroupCount').value)||2,names=shuffled(rosterNames()),groups=Array.from({length:count},()=>[]);names.forEach((name,i)=>groups[i%count].push(name));seatEl('#seatingGroupResults').innerHTML=groups.map((group,i)=>`<section><strong>Group ${i+1}</strong><p>${group.join('<br>')||'—'}</p></section>`).join('')}
function importRoster(file){const reader=new FileReader();reader.onload=()=>{let rows=String(reader.result||'').split(/\r?\n/).map(row=>row.split(',')[0].replace(/^\s*["']|["']\s*$/g,'').trim()).filter(Boolean);if(/^(student|name|student name)$/i.test(rows[0]||''))rows.shift();seatingRoster.value=rows.slice(0,100).join('\n');showToast(`${Math.min(rows.length,100)} students imported`);queueSave()};reader.readAsText(file)}
function downloadChart(){const custom=seatingState.layoutMode==='custom',scale=2,cellW=180,cellH=100,pad=50,maxX=custom?Math.max(700,...seatingState.deskLayout.map(d=>d.x+d.w+pad)):Math.max(700,seatingState.columns*cellW+pad*2),maxY=custom?Math.max(650,...seatingState.deskLayout.map(d=>d.y+d.h+190)):190+seatingState.rows*cellH,width=maxX,height=maxY,canvas=document.createElement('canvas');canvas.width=width*scale;canvas.height=height*scale;const c=canvas.getContext('2d');c.scale(scale,scale);c.fillStyle='#f4f8fc';c.fillRect(0,0,width,height);c.fillStyle='#173868';c.font='bold 28px sans-serif';c.textAlign='center';c.fillText(seatingClassName.value||'My Class',width/2,42);c.fillRect(width*.25,65,width*.5,38);c.fillStyle='#fff';c.font='bold 14px sans-serif';c.fillText('FRONT OF ROOM',width/2,90);seatingState.seats.forEach((name,i)=>{const desk=custom?seatingState.deskLayout[i]:null,row=Math.floor(i/seatingState.columns),col=i%seatingState.columns,x=custom?(desk?.x||0)+pad:pad+col*cellW,y=custom?(desk?.y||0)+125:125+row*cellH,w=custom?(desk?.w||98):cellW-16,h=custom?(desk?.h||68):cellH-16;c.save();c.translate(x+w/2,y+h/2);c.rotate(((desk?.rotation||0)*Math.PI)/180);c.fillStyle=name?'#fff':'#e8eef5';c.strokeStyle=seatingState.locked[i]?'#e6a700':'#b8c9dc';c.lineWidth=3;c.beginPath();c.roundRect(-w/2,-h/2,w,h,12);c.fill();c.stroke();c.fillStyle='#173868';c.font='bold 16px sans-serif';c.fillText(name||'Empty',0,6,w-20);c.restore()});const link=document.createElement('a');link.download=`${(seatingClassName.value||'seating-chart').replace(/[^a-z0-9]+/gi,'-')}.png`;link.href=canvas.toDataURL('image/png');link.click()}
function setStorage(mode){seatingStorageMode=mode;localStorage.setItem('glnSeatingStorageMode',mode);seatingLocalMode.classList.toggle('active',mode==='local');seatingGoogleMode.classList.toggle('active',mode==='google');const signed=Boolean(currentUser&&!currentUser.isAnonymous);seatingGoogleSignIn.hidden=mode!=='google'||signed;if(mode==='local')saveLocal();else if(signed)loadCloud();else initializeAccount()}
async function initializeAccount(){try{await initRaceFirebase();if(currentUser&&!currentUser.isAnonymous){seatingGoogleSignIn.hidden=true;await loadCloud()}else{seatingGoogleSignIn.hidden=false;seatingStorageStatus.textContent='Sign in to sync all classes across devices'}}catch{seatingGoogleSignIn.hidden=false;seatingStorageStatus.textContent='Google sync is not configured yet.'}}
async function signInGoogle(){seatingGoogleSignIn.disabled=true;try{await initRaceFirebase();const provider=new fb.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const credential=await fb.signInWithPopup(auth,provider);currentUser=credential.user;seatingGoogleSignIn.hidden=true;await loadCloud()}catch{seatingStorageStatus.textContent='Google sign-in was not completed.'}finally{seatingGoogleSignIn.disabled=false}}
async function loadCloud(){if(!currentUser||currentUser.isAnonymous)return;try{const snapshot=await fb.get(fb.ref(db,`seatingCharts/${currentUser.uid}`));if(snapshot.exists()){const data=snapshot.val();if(Array.isArray(data.classes)&&data.classes.length){seatingClasses=data.classes.map(normalize);activeClassId=data.activeClassId||seatingClasses[0].id;applyState(seatingClasses.find(c=>c.id===activeClassId)||seatingClasses[0])}}else await saveCloud();seatingStorageStatus.textContent=`Synced with ${currentUser.email||'Google account'}`;seatingStorageStatus.classList.add('synced')}catch{seatingStorageStatus.textContent='Could not load the cloud copy.'}}
function selectedDeskIndexes(){return seatingState.deskLayout.map((desk,index)=>selectedDesks.has(desk.id)?index:-1).filter(index=>index>=0)}
function addDesk(){pushDeskHistory();if(seatingState.layoutMode!=='custom')gridToCustom();const index=seatingState.deskLayout.length,spot=findOpenDeskSpot(98,68);if(!spot){deskUndo.pop();showToast('No open space for another desk');return}const desk={id:`desk-${Date.now()}-${index}`,...spot,w:98,h:68,rotation:0};seatingState.deskLayout.push(desk);seatingState.seats.push(null);seatingState.locked.push(false);selectedDesks=new Set([desk.id]);layoutEditing=true;renderSeatingChart();queueSave()}
function deleteSelectedDesks(){const indexes=selectedDeskIndexes().sort((a,b)=>b-a);if(!indexes.length){showToast('Select a desk first');return}pushDeskHistory();indexes.forEach(index=>{seatingState.deskLayout.splice(index,1);seatingState.seats.splice(index,1);seatingState.locked.splice(index,1)});selectedDesks.clear();renderSeatingChart();queueSave()}
function duplicateSelectedDesk(){const index=selectedDeskIndexes()[0];if(index===undefined){showToast('Select a desk first');return}const source=seatingState.deskLayout[index],spot=findOpenDeskSpot(source.w,source.h,source.x+20,source.y+20,new Set(),source.rotation||0);if(!spot){showToast('No open space to duplicate this desk');return}pushDeskHistory();const desk={...source,...spot,id:`desk-${Date.now()}`};seatingState.deskLayout.push(desk);seatingState.seats.push(null);seatingState.locked.push(false);selectedDesks=new Set([desk.id]);renderSeatingChart();queueSave()}
function rotateSelected(){const indexes=selectedDeskIndexes();if(!indexes.length){showToast('Select a desk first');return}const changes=new Map(indexes.map(index=>{const desk=seatingState.deskLayout[index];return[desk.id,{...desk,rotation:((desk.rotation||0)+15)%360}]}));if(!validDeskChanges(changes)){flashDeskCollision();showToast('Not enough space to rotate these desks');return}pushDeskHistory();applyDeskChanges(changes);renderSeatingChart();queueSave()}
function resetToGrid(){pushDeskHistory();seatingState.layoutMode='grid';layoutEditing=false;selectedDesks.clear();const count=seatingState.rows*seatingState.columns;seatingState.seats=seatingState.seats.slice(0,count);while(seatingState.seats.length<count)seatingState.seats.push(null);seatingState.locked=seatingState.locked.slice(0,count);while(seatingState.locked.length<count)seatingState.locked.push(false);renderSeatingChart();queueSave()}
function toggleLayoutEditor(){if(seatingState.layoutMode!=='custom'){pushDeskHistory();gridToCustom();layoutEditing=true}else layoutEditing=!layoutEditing;selectedDesks.clear();renderSeatingChart();queueSave()}
function undoDeskEdit(){if(!deskUndo.length)return;deskRedo.push(deskSnapshot());restoreDeskSnapshot(deskUndo.pop())}
function redoDeskEdit(){if(!deskRedo.length)return;deskUndo.push(deskSnapshot());restoreDeskSnapshot(deskRedo.pop())}
function uniqueClassName(base){let name=base,number=2;while(seatingClasses.some(item=>item.className===name))name=`${base} ${number++}`;return name}
function duplicateCurrentClass(){saveLocal();const copy=normalize(JSON.parse(JSON.stringify(seatingState)));copy.id=`class-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;copy.className=uniqueClassName(`${seatingState.className} Copy`);copy.deskLayout=copy.deskLayout.map((desk,index)=>({...desk,id:`desk-${Date.now()}-${index}`}));copy.updatedAt=Date.now();seatingClasses.push(copy);applyState(copy);queueSave();showToast('Class duplicated')}
function useAnotherClassLayout(){const source=seatingClasses.find(item=>item.id===seatEl('#seatingLayoutSource').value);if(!source){showToast('Choose another class first');return}capture();pushDeskHistory();seatingState.layoutMode=source.layoutMode;seatingState.rows=source.rows;seatingState.columns=source.columns;seatingState.flipped=source.flipped;seatingState.roomWidth=source.roomWidth;seatingState.roomHeight=source.roomHeight;seatingState.roomPreset=source.roomPreset;seatingRows.value=source.rows;seatingColumns.value=source.columns;seatEl('#roomWidth').value=source.roomWidth;seatEl('#roomHeight').value=source.roomHeight;seatEl('#roomPreset').value=source.roomPreset;seatingState.deskLayout=source.deskLayout.map((desk,index)=>({...desk,id:`desk-${Date.now()}-${index}`}));const count=source.layoutMode==='custom'?seatingState.deskLayout.length:source.rows*source.columns;seatingState.seats=seatingState.roster.slice(0,count);while(seatingState.seats.length<count)seatingState.seats.push(null);seatingState.locked=Array(count).fill(false);layoutEditing=false;selectedDesks.clear();renderSeatingChart();queueSave();showToast(`Layout copied from ${source.className}`)}
function findOpenDeskSpot(w=98,h=68,startX=20,startY=20,ignored=new Set(),rotation=0){const candidates=[];for(let y=0;y+h<=seatingState.roomHeight;y+=10)for(let x=0;x+w<=seatingState.roomWidth;x+=10)candidates.push({x,y,distance:Math.hypot(x-startX,y-startY)});candidates.sort((a,b)=>a.distance-b.distance);for(const point of candidates){const candidate={id:'candidate',x:point.x,y:point.y,w,h,rotation};if(insideRoom(candidate)&&seatingState.deskLayout.every(desk=>ignored.has(desk.id)||!overlaps(candidate,desk)))return{x:point.x,y:point.y}}return null}
function repairExistingOverlaps(){if(!seatEl('#preventDeskOverlap').checked)return 0;let repaired=0;for(let index=0;index<seatingState.deskLayout.length;index++){const desk=seatingState.deskLayout[index],conflicts=seatingState.deskLayout.slice(0,index).some(other=>overlaps(desk,other));if(!conflicts&&insideRoom(desk))continue;const spot=findOpenDeskSpot(desk.w,desk.h,desk.x,desk.y,new Set([desk.id]),desk.rotation||0);if(spot){desk.x=spot.x;desk.y=spot.y;repaired++}else flashDeskCollision(new Set([desk.id]))}return repaired}
function copySelectedDesks(){const indexes=selectedDeskIndexes();if(!indexes.length)return;deskClipboard=indexes.map(index=>({desk:{...seatingState.deskLayout[index]},name:seatingState.seats[index],locked:seatingState.locked[index]}));showToast(`${indexes.length} desk${indexes.length===1?'':'s'} copied`)}
function pasteDesks(){if(!deskClipboard?.length)return;pushDeskHistory();const added=[];for(const item of deskClipboard){const spot=findOpenDeskSpot(item.desk.w,item.desk.h,item.desk.x+20,item.desk.y+20,new Set(),item.desk.rotation||0);if(!spot){showToast('No open space for more desks');break}const desk={...item.desk,...spot,id:`desk-${Date.now()}-${Math.random().toString(36).slice(2,6)}`};seatingState.deskLayout.push(desk);seatingState.seats.push(item.name);seatingState.locked.push(item.locked);added.push(desk.id)}selectedDesks=new Set(added);renderSeatingChart();queueSave()}
function moveSelectedByKeyboard(dx,dy){if(!selectedDesks.size)return;const changes=new Map(seatingState.deskLayout.filter(item=>selectedDesks.has(item.id)).map(item=>[item.id,{...item,x:item.x+dx,y:item.y+dy}]));if(!validDeskChanges(changes)){flashDeskCollision();return}pushDeskHistory();applyDeskChanges(changes);renderSeatingChart();queueSave()}
const roomPresets={small:[600,400],medium:[760,520],large:[1000,700],wide:[1200,560],square:[760,760]};
function setRoomPreset(){const preset=seatEl('#roomPreset').value;if(roomPresets[preset]){pushDeskHistory();[seatingState.roomWidth,seatingState.roomHeight]=roomPresets[preset];const neededWidth=Math.max(500,...seatingState.deskLayout.map(d=>d.x+d.w+20)),neededHeight=Math.max(360,...seatingState.deskLayout.map(d=>d.y+d.h+20));seatingState.roomWidth=Math.max(seatingState.roomWidth,neededWidth);seatingState.roomHeight=Math.max(seatingState.roomHeight,neededHeight);seatEl('#roomWidth').value=seatingState.roomWidth;seatEl('#roomHeight').value=seatingState.roomHeight;renderSeatingChart();queueSave()}}
function updateRoomInputs(){pushDeskHistory();const neededWidth=Math.max(500,...seatingState.deskLayout.map(d=>d.x+d.w+20)),neededHeight=Math.max(360,...seatingState.deskLayout.map(d=>d.y+d.h+20));seatingState.roomWidth=Math.max(neededWidth,Math.min(2000,Number(seatEl('#roomWidth').value)||760));seatingState.roomHeight=Math.max(neededHeight,Math.min(1400,Number(seatEl('#roomHeight').value)||520));seatingState.roomPreset='custom';seatEl('#roomPreset').value='custom';seatEl('#roomWidth').value=seatingState.roomWidth;seatEl('#roomHeight').value=seatingState.roomHeight;renderSeatingChart();queueSave()}
function beginRoomResize(event){if(!layoutEditing||seatingState.layoutMode!=='custom')return;event.preventDefault();pushDeskHistory();const sx=event.clientX,sy=event.clientY,ow=seatingState.roomWidth,oh=seatingState.roomHeight,neededWidth=Math.max(500,...seatingState.deskLayout.map(d=>d.x+d.w+20)),neededHeight=Math.max(360,...seatingState.deskLayout.map(d=>d.y+d.h+20));const move=e=>{seatingState.roomWidth=Math.max(neededWidth,Math.min(2000,ow+(e.clientX-sx)/currentRoomScale));seatingState.roomHeight=Math.max(neededHeight,Math.min(1400,oh+(e.clientY-sy)/currentRoomScale));seatingState.roomPreset='custom';seatEl('#roomPreset').value='custom';seatEl('#roomWidth').value=Math.round(seatingState.roomWidth);seatEl('#roomHeight').value=Math.round(seatingState.roomHeight);renderSeatingChart()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);queueSave()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
const shortcutRows=[['Undo','⌘/Ctrl Z'],['Redo','⌘/Ctrl Shift Z'],['Select all desks','⌘/Ctrl A'],['Copy desks','⌘/Ctrl C'],['Paste desks','⌘/Ctrl V'],['Duplicate desks','⌘/Ctrl D'],['Delete desks','Delete/Backspace'],['Move 1 pixel','Arrow keys'],['Move 10 pixels','Shift + Arrow'],['Rotate desks','R'],['Lock or unlock','L'],['Edit layout','E'],['Clear selection','Esc'],['Save','⌘/Ctrl S'],['Disable smart snap temporarily','Hold Option/Alt']];
function setupShortcutDialog(){seatEl('#deskShortcutList').innerHTML=shortcutRows.map(([action,key])=>`<div><span>${action}</span><kbd>${key}</kbd></div>`).join('')}
function seatingShortcut(event){if(seatEl('#seatingPanel').hidden)return;const target=event.target;if(/INPUT|TEXTAREA|SELECT/.test(target.tagName)||target.isContentEditable)return;const mod=event.metaKey||event.ctrlKey,key=event.key.toLowerCase();if(key==='f'&&!mod){event.preventDefault();fitSeatingRoom();return}if(key==='e'&&!mod){event.preventDefault();toggleLayoutEditor();return}if(key==='escape'){seatEl('#seatingPanel').classList.remove('classes-open','inspector-open');selectedDesks.clear();refreshDeskSelection();return}if(!layoutEditing)return;if(mod&&key==='z'){event.preventDefault();event.shiftKey?redoDeskEdit():undoDeskEdit();return}if((event.ctrlKey&&key==='y')){event.preventDefault();redoDeskEdit();return}if(mod&&key==='a'){event.preventDefault();selectedDesks=new Set(seatingState.deskLayout.map(d=>d.id));refreshDeskSelection();return}if(mod&&key==='c'){event.preventDefault();copySelectedDesks();return}if(mod&&key==='v'){event.preventDefault();pasteDesks();return}if(mod&&key==='d'){event.preventDefault();duplicateSelectedDesk();return}if(mod&&key==='s'){event.preventDefault();queueSave();showToast('Layout saved');return}if(key==='delete'||key==='backspace'){event.preventDefault();deleteSelectedDesks();return}if(key==='r'){event.preventDefault();rotateSelected();return}if(key==='l'){event.preventDefault();const indexes=selectedDeskIndexes();if(indexes.length){pushDeskHistory();const lock=!indexes.every(i=>seatingState.locked[i]);indexes.forEach(i=>seatingState.locked[i]=lock);renderSeatingChart();queueSave()}return}const arrows={arrowleft:[-1,0],arrowright:[1,0],arrowup:[0,-1],arrowdown:[0,1]};if(arrows[key]){event.preventDefault();const amount=event.shiftKey?10:1;moveSelectedByKeyboard(arrows[key][0]*amount,arrows[key][1]*amount)}}
function setupDeskTooltips(){const toggle=seatEl('#deskTooltips'),tooltip=seatEl('#deskTooltip'),mac=/Mac|iPhone|iPad/.test(navigator.platform);toggle.checked=localStorage.getItem('glnDeskTooltips')!=='off';let timer;document.addEventListener('pointerover',event=>{const target=event.target.closest('[data-tip]');if(!target||!toggle.checked)return;clearTimeout(timer);timer=setTimeout(()=>{const [text,key]=target.dataset.tip.split('|');tooltip.innerHTML=`<strong>${text}</strong>${key?`<kbd>${key.replace('mod',mac?'⌘':'Ctrl')}</kbd>`:''}`;tooltip.hidden=false;const box=target.getBoundingClientRect();tooltip.style.left=`${Math.min(window.innerWidth-240,Math.max(8,box.left))}px`;tooltip.style.top=`${Math.min(window.innerHeight-70,box.bottom+8)}px`},350)});document.addEventListener('pointerout',event=>{if(event.target.closest('[data-tip]')){clearTimeout(timer);tooltip.hidden=true}});toggle.onchange=()=>{localStorage.setItem('glnDeskTooltips',toggle.checked?'on':'off');tooltip.hidden=true}}
function setupSeatingWorkspace(){const inspector=seatEl('#seatingInspector'),left=seatEl('#seatingClassPanel');left.querySelectorAll('.inspector-control,.layout-editor,.seating-rules,.seating-groups,.seating-help').forEach(node=>inspector.append(node));const panel=seatEl('#seatingPanel'),syncVisibility=()=>{const active=!panel.hidden;document.body.classList.toggle('seating-workspace-active',active);if(active)requestAnimationFrame(fitSeatingRoom)};new MutationObserver(syncVisibility).observe(panel,{attributes:true,attributeFilter:['hidden']});syncVisibility();seatEl('#toggleClassPanel').onclick=()=>panel.classList.toggle('classes-open');seatEl('#closeClassPanel').onclick=()=>panel.classList.remove('classes-open');seatEl('#toggleInspectorPanel').onclick=()=>panel.classList.toggle('inspector-open');seatEl('#closeInspectorPanel').onclick=()=>panel.classList.remove('inspector-open');seatEl('#toggleSeatingPanels').onclick=()=>{panel.classList.toggle('view-only');seatEl('#toggleSeatingPanels').textContent=panel.classList.contains('view-only')?'Show panels':'View only';requestAnimationFrame(fitSeatingRoom)};seatEl('#fitSeatingRoom').onclick=fitSeatingRoom;seatEl('#seatingZoomOut').onclick=()=>changeSeatingZoom(-.1);seatEl('#seatingZoomIn').onclick=()=>changeSeatingZoom(.1);seatEl('#quickBuildSeating').onclick=()=>seatEl('#buildSeating').click();seatEl('#quickShuffleSeating').onclick=()=>seatEl('#shuffleSeating').click();seatEl('#quickEditLayout').onclick=()=>seatEl('#editDeskLayout').click();seatingRoster.addEventListener('input',updateRosterCount)}
setupSeatingWorkspace();
seatEl('#resetDeskGrid').hidden=true;seatEl('#preventDeskOverlap').checked=false;seatEl('#preventDeskOverlap').closest('label').hidden=true;seatEl('#snapDesks').closest('label').lastChild.textContent=' Snap movement';
const saved=JSON.parse(localStorage.getItem('glnSeatingClasses')||'null');if(saved?.classes?.length){seatingClasses=saved.classes.map(normalize);activeClassId=saved.activeClassId||seatingClasses[0].id}else{const legacy=JSON.parse(localStorage.getItem('glnSeatingChart')||'null'),initial=normalize(legacy||{className:'My Class',roster:defaultRoster});seatingClasses=[initial];activeClassId=initial.id}applyState(seatingClasses.find(c=>c.id===activeClassId)||seatingClasses[0]);
seatingClassSelect.onchange=()=>switchSeatingClass(seatingClassSelect.value);seatEl('#newSeatingClass').onclick=()=>{saveLocal();const item=blankClass(`Class ${seatingClasses.length+1}`);seatingClasses.push(item);manualRoomScale=null;applyState(item);queueSave()};seatEl('#duplicateSeatingClass').onclick=duplicateCurrentClass;seatEl('#useClassLayout').onclick=useAnotherClassLayout;seatEl('#deleteSeatingClass').onclick=()=>{if(seatingClasses.length===1){showToast('Keep at least one class');return}if(!confirm(`Delete ${seatingState.className}?`))return;seatingClasses=seatingClasses.filter(c=>c.id!==activeClassId);manualRoomScale=null;applyState(seatingClasses[0]);queueSave()};
seatEl('#buildSeating').onclick=buildChart;seatEl('#shuffleSeating').onclick=shuffleChart;seatEl('#flipSeating').onclick=()=>{seatingState.flipped=!seatingState.flipped;renderSeatingChart();queueSave()};seatEl('#editDeskLayout').onclick=toggleLayoutEditor;seatEl('#resetDeskGrid').onclick=resetToGrid;seatEl('#addDesk').onclick=addDesk;seatEl('#deleteDesk').onclick=deleteSelectedDesks;seatEl('#duplicateDesk').onclick=duplicateSelectedDesk;seatEl('#rotateDesk').onclick=rotateSelected;seatEl('#undoDesk').onclick=undoDeskEdit;seatEl('#redoDesk').onclick=redoDeskEdit;seatEl('#makeSeatingGroups').onclick=createGroups;seatEl('#importSeatingRoster').onclick=()=>seatEl('#seatingFileInput').click();seatEl('#seatingFileInput').onchange=e=>{if(e.target.files[0])importRoster(e.target.files[0]);e.target.value=''};seatEl('#downloadSeating').onclick=downloadChart;seatingLocalMode.onclick=()=>setStorage('local');seatingGoogleMode.onclick=()=>setStorage('google');seatingGoogleSignIn.onclick=signInGoogle;seatEl('#seatingFullscreen').onclick=()=>{if(!document.fullscreenElement)seatEl('#seatingPanel').requestFullscreen?.();else document.exitFullscreen?.()};seatEl('#printSeating').onclick=()=>{document.body.classList.add('print-seating');window.print()};window.addEventListener('afterprint',()=>document.body.classList.remove('print-seating'));[seatingClassName,seatingRoster,seatEl('#seatingKeepApart'),seatEl('#seatingNearFront'),seatEl('#seatingGroupA'),seatEl('#seatingGroupB')].forEach(input=>input.addEventListener('change',queueSave));seatEl('#seatingAlternateGender').onchange=queueSave;setStorage(seatingStorageMode);window.renderSeatingChart=renderSeatingChart;
seatEl('#roomPreset').onchange=setRoomPreset;seatEl('#roomWidth').onchange=updateRoomInputs;seatEl('#roomHeight').onchange=updateRoomInputs;seatEl('#roomResizeHandle').onpointerdown=beginRoomResize;[seatEl('#snapDesks'),seatEl('#smartGuides')].forEach(input=>input.onchange=queueSave);seatEl('#preventDeskOverlap').onchange=()=>{if(seatEl('#preventDeskOverlap').checked){pushDeskHistory();const count=repairExistingOverlaps();renderSeatingChart();if(count)showToast(`${count} overlapping desk${count===1?' was':'s were'} moved apart`)}queueSave()};seatEl('#showDeskShortcuts').onclick=()=>seatEl('#deskShortcutDialog').showModal();document.addEventListener('keydown',seatingShortcut);document.addEventListener('fullscreenchange',()=>requestAnimationFrame(updateRoomScale));window.addEventListener('resize',()=>requestAnimationFrame(updateRoomScale));setupShortcutDialog();setupDeskTooltips();
